### ISSUE TITLE
Manifestations of copyrastic idiocy should be excluded from Waterfox builds

### ISSUE THREAD

**Issue by powerbroker** [MrAlex94/Waterfox#11]
When Waterfox is installed, there is a piece of third-party(!) bloatware(!) "primetime content decryption module provided by abdolbe..." implementing copyrastic idiocy concepts(!) integrated(!!!) and enabled by default(!!!).

The copyright morons must care about their shitware themselves. They and only they must integrate it and distribute. Nobody else(since nobody else need it).

Waterfox builds should be based on the EME-free version, and 'media.eme.enabled' config option should be 'false' by default.
A special note for those who are infected by copyrastic idiocy, describing the way they can enable it, may be provided.

**Comment by DaAwesomeP** [comment]
From what I've seen so far, the intention of Waterfox is to be a 64-bit version of Firefox and nothing less. Otherwise the fork would split very far and have to be managed much more.

It is enabled by default in the regular version of Firefox. That isn't bloatware. It's a Mozilla approved plugin that is automatically downloaded like Cisco's H.264 codec plugin. It is downloaded separately from another server to maintain the open source nature of the Mozilla codebase, since those parts can't be open source for security or other lawful reasons. Other browsers like Chrome already have this implemented. Chrome doesn't need Silverlight for instance anymore to play Netflix. It's all native HTML5. The EME is only enabled when a website wants it, so I don't see a problem with it.

Last time I checked, there isn't a 64-bit version of it available, so it shouldn't work in Waterfox anyways. There's also a much easier to use option in the settings page instead of about:config.

**Comment by MrAlex94** [comment]
Everything that DaAwesomeP has said is correct so far, but if you have any other questions I don't mind helping.
