### ISSUE TITLE
YouTube polymer (layout/rendering) sometimes not working with Waterfox Classic 2019.10

### ISSUE THREAD

**Issue by grahamperrin** [MrAlex94/Waterfox#1206]
#1205 is for **playback**, with symptoms that are (to me) **consistently reproducible**. There's a comment re: a change to service by YouTube. 

----

This issue #1206 is distinct, for **polymer**, with symptoms that may be **not** consistently reproducible.  

From this morning's [Youtube suddenly not loading properly : waterfox](https://www.reddit.com/r/waterfox/comments/diynta/youtube_suddenly_not_loading_properly/) it appears that issues with (or affecting) polymer in YouTube with 56.2.14 may be transient. 

I have **not** _yet_ found this issue with either: 

- 56.2.14 (20190903144949) on Manjaro
- 56.2.14 (20191007063316) on FreeBSD-CURRENT. 

From what I have seen so far, with 2019.10, some of the **non**-reproducibility or apparent randomness may be attributable to e.g. caching so it's important to: 

- <kbd>Control</kbd>-<kbd>F5</kbd> (FreeBSD, Linux, Windows) or <kbd>Command</kbd>-<kbd>Shift</kbd>-<kbd>R</kbd> (Mac OS X) or <kbd>Shift</kbd>-Reload before drawing conclusion from any test result. 

I have screenshots, and at least one screen recording, but I'll not rush to make any attachment to this issue. Early hours of the morning. Sleep required!

Meta, tracking: #538

**Comment by colin1951uk** [comment]
Could I just come in on this thread rather than open a new one please.

Referring to the Windows Classic Release.

I'm not technically familiar with the term 'polymer layering,' but from a version of Waterfox that I downloaded from a thread on here late yesterday my time i.e. 56.3.0.7227 (I can't figure out the build number) I'm finding that Live Streams on YouTube eg: Sky News Live and Nasa Tv Live etc etc do work, but Uploaded Videos do not.  

The Live streams may take take 30 seconds or so to kick in but they do eventually come alive. Uploaded Videos just give a black screen and the forever rotating white circle.

I have tried cache clearing but nothing changes.

56.2.14 works perfectly for any Video I try and the Live stuff comes up instantaneously. 

Also 56.3.0.7227 is now compatible with my add ons (related thread deleted) and all are now working, so kudos for that.

Just thought I'd say something to backup the original poster, if it's not helpful (or out of order) feel free to delete everything said.

**Comment by grahamperrin** [comment]
> 56.3.0.7227

On a Mac, yes?

> … if it's not helpful (or out of order) …

Thanks, :-) it's off-topic (OT) but I wouldn't describe it as out of order. If you like, you can probably hide it (as off-topic) using the hamburger menu at the head of your comment. 

What you describe seems playback-related, so it might belong under #1205 although I can not yet describe either #1205 or this bug #1206 as _verified_. 

When people mention _polymer_ in connection with problems with YouTube, it's for this type of thing (the window to the right): 

![2019-10-17 01:30:38](https://user-images.githubusercontent.com/192271/67062429-30874480-f15b-11e9-8ecd-f95c201a4ff0.png)

- 2019-10-17 01:30:38 (around 26.5 hours ago)

https://www.reddit.com/comments/diynta/-/f41brsd/ (around thirteen hours ago) shows no further problem with polymer for a user of Waterfox Classic 56.2.14 so it's reasonable to assume that the problem was server-side, with YouTube. 

At the time of writing I can not re-run the virtual machines that I use to test Waterfox Classic 2019.10 so personally, I can not yet make the same assumption (sorry, folks) … 

----

https://redd.it/djceyv noted with thanks re: the push back.

**Comment by grahamperrin** [comment]
> can't figure out the build number

Visit this address, in Waterfox: 

- about:support

The _Troubleshooting information_ page has an _Application basics_ section that includes the build ID. 

The troubleshooting page is also available through the Help menu.

**Comment by grahamperrin** [comment]
> … reasonable to assume that the problem was server-side, with YouTube. …

This morning I could not reproduce the issue on Manjaro with: 

- Waterfox Classic 2019.10 (20191015002329)
- Waterfox Classic 56.2.14 (20190903144949).

Respectively: 

![2019-10-19 11:09:41](https://user-images.githubusercontent.com/192271/67146922-fd8e9f00-f287-11e9-97f9-7fbc89d7bc8b.png)

![2019-10-19 11:11:37](https://user-images.githubusercontent.com/192271/67146930-1434f600-f288-11e9-8369-1d9e7a0934c8.png)
