### ISSUE TITLE
Lib6 requirement?

### ISSUE THREAD

**Issue by Achaean** [MrAlex94/Waterfox#1237]
Couldn't launch Current branch.
Here's console's output:
```
>./waterfox
XPCOMGlueLoad error for file /home/giorgos/waterfox/liblgpllibs.so:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/giorgos/waterfox/liblgpllibs.so)
Couldn't load XPCOM.
>

```
I think Lib6 2.27 should be added to the requirements.
(I'm on a Debian oldstable based distro).

**Comment by laniakea64** [comment]
https://github.com/MrAlex94/Waterfox/issues/1128

**Comment by hawkeye116477** [comment]
@Achaean Just use my package => https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-current-kpe :smile:. It's compiled with PGO+LTO, so should work even better than official. Also there are langpacks in packages `waterfox-current-i18n-langcode`.

**Comment by Achaean** [comment]
**THANKS** hawkeye!!!
Already did it!  :-)

**Comment by hawkeye116477** [comment]
In the past statically linking helped, but here is problem with glibc, which shouldn't be rather statically linked, so @MrAlex94 should build it on some older distro or maybe write that glibc 2.27 is required or put link to my AppImage (https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/waterfox-current-latest-x86_64.AppImage.mirrorlist), which only requires clicking on it to be launched, but can be also unpacked and it was built on CentOS 7, so compatibility is even better than in case of Official Classic tar.
But with AppImage currently are 2 problems => on some distros it creates new profile every launch or maybe that's something wrong with my VM image, cuz on Manjaro it doesn't do that and problem no 2 is that it checks for updates on `waterfox.net`, not on OBS, so that should be patched to maybe use libappimageupdate for update checking.
