### ISSUE TITLE
2019-10-Classic breaks ImageHost-Grabber because of missing Object.prototyp.watch

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1238]
Imagehost-Grabber 1.7.0.4b does not work with 2019-10-Classic.
The browser console shows the error message "TypeError: this.watch is not a function"

I patched my local Imagehost-Grabber by adding a polyfill for Object.prototype.watch (https://gist.github.com/eligrey/384583). Now it works again. 

Is it possible to add Object.watch back again or was it removed intentionally?

The commit that removed watch:
https://github.com/MrAlex94/Waterfox/commit/8f87cbc0938fec17726dd09b4af2648c084fdbf7#diff-0daec3665984e3f5935318a48f8080c3

**Comment by hawkeye116477** [comment]
That was removed, because that was breaking some websites like `mlb.com`. Moonchild Productions(Basilisk, Pale Moon) also decided to do that.
https://github.com/MoonchildProductions/UXP/issues/1257
https://github.com/MoonchildProductions/UXP/issues/1235

Possible alternative is Bulk Media Downloader `https://addons.mozilla.org/pl/firefox/addon/bulk-media-downloader/`. I know, it has only 2 stars, but I don't know why it has that bad rating, for me works good.

Replacement for Object.prototype.watch exists (`https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy`).

**Comment by ghost** [comment]
okay, thank you very much for this info!

**Comment by cblknittights** [comment]
And what version of PaleMoon has this break so we can alert our IHG users to not use that version?

**Comment by SpockFan02** [comment]
Most likely the upcoming 28.8.0 release @cblknittights https://forum.palemoon.org/viewtopic.php?p=177327#p177286

**Comment by grahamperrin** [comment]
@JustOff

**Comment by dodona2** [comment]
https://github.com/SparkyBluefang/S4E/issues/55

**Comment by mattatobin** [comment]
@cblknittights

Are you seriously are going to advise your users to run an old and insecure version of their browser because you can't or won't be able to fix this issue in a month's time or so?

May I remind you that it is the responsibility of extensions to be compatible with applications not the other way around?

**Comment by cblknittights** [comment]
YES WE HAVE and WILL be advising users to use a version of the browser that works.

We do NOT HAVE A DEVELOPER to change a CORE CODE section. We have not had one in 5 YEARS.

My site and team provide ONLY UPDATES to the hostf.xml file to add/correct/update hosts as needed.

So unless some one is going to step into the role of developing a fix for this... Are your offering to develop a fix for this for IHG??????

then YES THE ONLY RECOURSE is to use a browser that works. I use FF < 54 and actually use 10.x something for 99% of what I do... PM 27.x something as well...

**Comment by mattatobin** [comment]
With the polyfill code readily available as well as documentation on using the more standard technique anyone should come up with something.

However, and yes I totally get it especially coming from me.. but I do not wish to help you because of your aggressive and generally bad attitude.

I would suggest, though, you reconsider your course of action.

**Comment by ghost** [comment]
I made a quick and dirty fix here: https://github.com/tzr7/ImageHost-Grabber/commit/9764a2a28d0aac2af14f9837af096909c59d4f9b

Maybe I can do a clean and proper one and create a pull request. Let's move this discussion to IHG, it seems a bit off topic here.

**Comment by cblknittights** [comment]
>I made a quick and dirty fix here: tzr7/ImageHost-Grabber@9764a2a

>Maybe I can do a clean and proper one and create a pull request. Let's move this discussion to >IHG, it seems a bit off topic here.

Yes, please lets move to a better spot. And we need to be working on the 1.74**c** code.. which is NOT in our github... 

And THANK YOU for you interest and support. 
https://imagehostgrabber.com/forum/viewtopic.php?f=5&t=615

I guess we'll start there. and go from there...
