### ISSUE TITLE
Session Manager breaks on 2019.10

### ISSUE THREAD

**Issue by DrIT2016** [MrAlex94/Waterfox#1254]
I have multiple sessions in Session Manager. Which save separately as windows, so when i have 2 different sessions with tabs in 2 windows, adding/removing tabs on one window will save that in that window, same as the other. All get saved when closing window or browser.
Now with new (classic) version sessions don't get saved anymore on exit, so after restart i loose all my changes in tabs. Will revert back to Waterfox 56.2.14 as this is not a working situation. Hopefully this can be fixed.

**Comment by grahamperrin** [comment]
> … separately as windows … sessions don't get saved anymore on exit, …

I can't reproduce this with late October build 20191015002329 of Waterfox Classic 2019.10 on Manjaro Linux. 

A screen recording, watch from around 04:20 on the timeline: 

[2019-11-03 10:56 Session Manager auto-saving window sessions in Waterfox Classic 2019.10.zip](https://github.com/MrAlex94/Waterfox/files/3801481/2019-11-03.10.56.Session.Manager.auto-saving.window.sessions.in.Waterfox.Classic.2019.10.zip)

– note, a specified interval for auto-save: 

![2019-11-03 11:00:49 frame](https://user-images.githubusercontent.com/192271/68084209-8a119380-fe2a-11e9-8c94-e28533351242.png)

**Comment by DrIT2016** [comment]
Hi grahamperrin,

First thanks for trying to reproduce extensively.

You are using the 1 minute interval if i understand video correctly? This is what i also did to at least not loose everything. But in old version i could enter the value 0 (with also setted setting "treat closing last windows as exit"). Now this value can't be entered anymore. Also when saving current window and entering already existing name, it will save new file with increasing number (e.a. "Last-2" instead of entered "Last" as name) instead of giving option to overwrite existing session.

Now when you f.e. add 2 new tabs and immediately exit (instead of waiting the 1 minute interval) it will not save it in session. So will only save every 1 minute instead of also on exit window.
The workaround of 1 minute btw is saving it very minute instead of only save on exit which i used all that time.

Btw i'm using it on Windows 8.1 and have Waterfox build number 20191022125504.

**Comment by grahamperrin** [comment]
> in old version i could enter the value 0 

Here with Waterfox Classic 56.2.14, `0` is not an allowed interval for auto-saving a window:

![image](https://user-images.githubusercontent.com/192271/68086971-437f6180-fe49-11e9-857b-80992914301a.png)

**Comment by DrIT2016** [comment]
Will check that out again when i have reverted (maybe leftover from way back?)
But can you confirm it doesn't save anymore on exit while it did in older version?

**Comment by grahamperrin** [comment]
> … can you confirm it doesn't save anymore on exit … 

02:11 on the timeline, I quit then started the application, windows and tabs were restored (in the traditional way). 

The two saved windows were as they were when I saved them. 

Honestly, I have no past recollection of window-specific sessions saving automatically at quit time. I'm fairly certain of this because on the rare occasions when I worked with window-specific sessions in the past, I sensed a need to either (a) manually save or (b) auto-save. I mean: 

- I _never_ expected a **non**-automated session to automatically save in any situation.

**Comment by DrIT2016** [comment]
At 2:11 it is almost (or already) 1 minute pass, so it will save the 1 minute auto save maybe?
Also the way you do it by closing fox and opening both windows afterwards, looks like is saves both windows in one session?

Can you please try one more time? 
Problem can also be seen in 1 window. So now open fox, open couple of tabs and save as window. Now also set session manager to always open this specific session on startup (my personal setting, so always one window opens, no matter if on close you had multiple open). Close fox and open again (it should open this session). Now immediately change some tabs en close direct after (when not succeed do it again right away). You can see f.e. on session file save date/time it is not saved...

Btw i have used this specific window session save for many years. So really sure it does save on exit (even when closing one window and keeping the other one open, it does save the changes of closed window in that corresponding window session). This was unique feature of session manager which no other session manager has adopted since quantum sadly.
Also saw it working on other pc (with 56.2.13 if i remembered correctly) with overwrite same name session and the number 0 in black, while after the update this was not working anymore.

**Comment by grahamperrin** [comment]
> At 2:11 it is almost (or already) 1 minute pass, so it will save the 1 minute auto save maybe?

At that time, no automation had been set. The two saved windows were manually saved.

**Comment by DrIT2016** [comment]
Ah ok manually saved instead of auto on close, this was not the issue ;)
But could you do it one more time as described please (preferably on Windows if you have that option)?

**Comment by grahamperrin** [comment]
Maybe next week. 

In the meantime: anyone else?

**Comment by ElhemEnohpi** [comment]
I can confirm that 2019.10 breaks Session Manager autosave and restoring of "window sessions" (as far as I can tell, regular multi-window sessions work as usual). A malfunctioniong Session Manager is a bit of a nightmare for me, as 95% of the reason I use Waterfox is for Session Manager's "window sessions", of which I have hundreds... I only noticed this today, so it means I've been silently losing all the changes to my window sessions for the past couple of weeks. I've reverted to 56.2.14 but I'm worried about using an out-of-date browser for security reasons. I hope this can be fixed! Running on macOS.

A note about the autosave setting: I don't specify a "save every x minutes" interval, but just leave it blank (that's probably what @DrIT2016 means rather than setting it to "0"). The "disabled if blank" message isn't very clear, it means that there won't be a timed update, but if the "make this an autosave session" box is checked, the Session Manager toolbar icon will be yellow, the window session name will show in the titlebar (enable titlebar in WF "customize") and Window menu (on Mac) and _it will be autosaved when closing the window_. For me, a timed update isn't necessary because restoring after a crash or quit is done by the built-in WF "show your windows and tabs from last time" session restore, which properly handles restoring Session Manager window sessions.

Steps to reproduce:

Creating a window session:
1. Create a new profile in WF 2019.10, install CAA and then Session Manager 0.8.1.13
2. In WF preferences choose "show your windows and tabs from last time".
3. In Session Manager options, uncheck "replace existing windows".
4. Create a new window, open some tabs.
5. Save it as a window session:
    1. Shift-click the Session Manager toolbar icon
    2. Choose a name and group
    3. Check the "make this an autosave session" box
    4. Leave "save every x minutes" blank

Expected results, as with all previous versions of Waterfox:
Toolbar icon turns yellow, session name appears in the icon tooltip on hover, and is appended to tab title in the titlebar and windows menu.

Actual results:
Icon turns yellow, tooltip shows session name, but session name is not shown in titlebar or windows menu.

Updating and autosaving:
6. Add or remove some tabs.
7. Close the window.

Expected results:
Window session is automatically updated on disk.

Actual results: 
Window session is not updated, changes are lost. Seems like maybe Session Manager doesn't get the message that the window has been closed, or maybe it gets a message but the window session name is missing from it?

Reopening/restoring the session:
8. Choose the window session from Session Manager's menu.

Expected results:
A window opens with the session's tabs (except the lost changes).

Actual results:
Nothing, not possible to open the window session unless you quit and restart WF. Session Manager behaves as though the window is still open.

Restarting Waterfox:
9. Repeat steps 1-6.
10. Quit Waterfox.
11. Re-open Waterfox.

Expected results:
All windows are restored by Waterfox, including changes, and window sessions are still active - the icon is yellow, the name is displayed, etc. The window sessions have been updated on disk.

Actual results:
All windows are restored by Waterfox, including changes. But window sessions are not active - the icon is not yellow, the name is not displayed, etc. The window sessions have not been updated on disk. If windows are closed, changes will be lost. It's possible at this point to re-save the windows using the same names, and clicking "replace session". You are then back at step 6.

Try to manually update a window session:
12. Repeat steps 1-6.
13. Add or remove some tabs.
14. Choose "Save and Close Window Session" from Session Manager menu.
15. Close the window (any further changes to it won't be saved).

Works as expected:
The window session is updated on disk, the icon is no longer yellow, and the session name is no longer displayed in the tooltip, titlebar, or window menu. The session can now be re-opened/restored as usual.

This could be used as a work-around of sorts, though it's very inconvenient compared to how it usually works: manually save each window session with "Save and Close Window Session"  before closing the window, and close all window sessions before quitting Waterfox. You'll then have to remember what windows you had open and manually re-open each one when starting WF again. Alternatively, I guess you could remember each open window's session name and re-save and replace each one after restarting WF (you'll have to do this if WF crashes and you restore it) - equally inconvenient. At this point I think I'll risk using the previous WF version until it can be fixed. Please let me know if there's anything else I can do...

**Comment by grahamperrin** [comment]
Worth noting (I don't seek a fix for these older issues, but the background preceding 2019.10 might help to refine the issue(s) with Session Manager in the 2019.10 environment): 

- [Recently closed windows (menu option) present but non-functional : waterfox](https://www.reddit.com/r/waterfox/comments/8o2e06/recently_closed_windows_menu_option_present_but/) (2018-06-02)
- [Session Manager sometimes saves only one tab at Waterfox quit time](https://www.reddit.com/r/waterfox/comments/awtdwj/session_manager_sometimes_saves_only_one_tab_at/) (2019-03-03)

**Comment by grahamperrin** [comment]
### Save Current Window

Now I see a difference between Waterfox Classic 56.2.14 and Waterfox Classic 2019.10 (20191023220600). 

Screen recording, Manjaro Linux: 

- [2019-11-14 06:10.zip](https://github.com/MrAlex94/Waterfox/files/3844924/2019-11-14.06.10.zip)
- https://put.re/player/MQcfZ89P.mp4

### Observations with Waterfox Classic 56.2.14

> **☑ Make this an auto-save session**

After opting to save: 

- the check disappears from the box
- the name of the window session disappears

![2019-11-14 06:10:56 frame](https://user-images.githubusercontent.com/192271/68833409-4b41d000-06ab-11ea-9cf1-fe6645c040cc.png)

![2019-11-14 06:10:57 frame](https://user-images.githubusercontent.com/192271/68833408-4b41d000-06ab-11ea-9480-ad371bda06f9.png)

The disappearances can be confusing but I guess, they're by design when the Session Manager window is kept open. 

As far I can tell, the automation occurs at quit time. 

> **Quit** (without saving)

Explicitly _avoiding_ the options to save the session: 

![2019-11-14 06:12:22 frame](https://user-images.githubusercontent.com/192271/68833703-079b9600-06ac-11ea-8733-d4009f5aacd1.png)

– seems to have no effect on the auto-saved window session, which was _not_ saved before quitting but _is_ saved when choosing to _not_ save the session. 

Getting my head around these UX contradictions made it easier to discover this feature of the extension. 

Also remarkable with 56.2.14: in the Session Manager window, for tabs that are added to the window, **titles are incorrect**. 

Two more frames from the same recording: 

![2019-11-14 06:11:35 frame](https://user-images.githubusercontent.com/192271/68835079-29e2e300-06af-11ea-806d-ab2a74a2f177.png)

![2019-11-14 06:11:38 frame](https://user-images.githubusercontent.com/192271/68835078-294a4c80-06af-11ea-9377-3baf80920edf.png)

I can't find [a report of that bug](https://www.mozdev.org/bugs/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&emailtype1=substring&emailassigned_to1=1&emailtype2=substring&emailreporter2=1&bugidtype=include&chfieldto=Now&product=sessionmanager&short_desc_type=allwordssubstr&long_desc_type=allwordssubstr&bug_file_loc_type=allwordssubstr&field0-0-0=noop&type0-0-0=noop&cmdtype=doit&order=Bug+Number). Was it specific to Session Manager with Waterfox Classic and if so … 

----

… is it contributory to whatever's bugging auto-saved window sessions for the extension with Waterfox Classic 2019.10?

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/compare/56.2.14...2019.10-classic-1

The [Session Manager support area was (understandably) locked in 2017](http://forums.mozillazine.org/viewtopic.php?p=14785199#p14785199) so we can't easily attract the attention of people who might have in-depth knowledge of the extension. I'll try an e-mail …

**Comment by ElhemEnohpi** [comment]
@grahamperrin thanks for taking the time to investigate. It's true there are a lot of options, and it's not always obvious how things work. 

"Window sessions" and "sessions" (i.e. all-windows) are different things. They're somewhat independent, and you can use either without the other if you want. Auto-save "window sessions" are auto-saved any time you close the window. At quit time, all windows are closed, and thus all window sessions are auto-saved. Except on WF 2019.10, neither of those things happen. Session Manager is no longer getting properly notified that a window has been closed so that it can auto-save it first - either the event is missing the window session name (which fits with the window titlebar also missing the name), or it's getting no signal at all, or it's too late and the window is already gone. The rest of the functionality is still working, because you can trigger it manually with "Save and Close Window Session" from the menu.

The dialog in the second screenshot, "do you want to preserve this _session_ for resuming" is about the overall "session". (Whether or not you see that prompt is controlled by the "at shutdown" option). It's not really related to any "window sessions" you may or may not have open, as they get independently auto-saved at quit, regardless of what you do with the overall "session". That's also expected behaviour.

You said:
> Explicitly _avoiding_ the options to save the session: – seems to have no effect on the auto-saved window session, which was _not_ saved before quitting but _is_ saved when choosing to _not_ save the session.

The named "window session" was saved once when you created it (with one tab) and again when the window was closed on quit, with three tabs. The "do you want to preserve this session" dialog has nothing to do with "window sessions".

Your observation that the checkbox and session name disappear after you save a window session is expected behaviour when you have "leave this window open" checked, which normally you don't... That option is mostly useful when renaming multiple sessions etc., but I guess you could also save multiple different window sessions at one time.

I can confirm that if you add a tab to a window while you have the "save current window" window open, the tab's title will be wrong in the display. I've never tried to do that before, normally you just go ahead and save the window session, and again, you don't keep the save dialog open... so probably nobody ever noticed it. Anyway it's just cosmetic, if you save it the title is correct. It doesn't seem very likely to have anything to do with this issue.

Thanks again for looking into it.

**Comment by grahamperrin** [comment]
Thanks, 

> Auto-save "window sessions" are auto-saved any time you close the window. 

Now I remember, using the feature a year or so ago, but I never relied upon it. (Not a problem with the extension; a problem with the underlying fragility of session storage.)

**Comment by ElhemEnohpi** [comment]
Just had some more time to look at it, the error messages I'm seeing in 2019.10, that are not present in 56.2.14, are related to the use of [`document.watch()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch), which apparently was deprecated and removed in Firefox 58. I assume a recent patch to Waterfox has made it stop working here too.

@MrAlex94 does that sound familiar? If so, is it possible it could be made to work again in Waterfox, or will the Session Manager addon need to be rewritten to use another method?

Commenting out the instances of `window.gBrowser.ownerDocument.watch/unwatch` allow Session Manager to work, but without the ability to see the session name in the window title/menu. Rather inconvenient, but not critical and at least I can use WF 2019.10 now. I'll try to find another way to detect changes to the window's titlebar, suggestions welcome...

These are the errors:
When starting up, just opening a window, without opening any session:
`TypeError: window.gBrowser.ownerDocument.watch is not a function[Learn More]  browserWindowOverlay.js:700:5`

Which points to this in browserWindowOverlay.js of Session Manager:
```
// Watch for changes to the titlebar so we can add our sessionname after it since 
// DOMTitleChanged doesn't fire every time the title changes in the titlebar.
// Don't watch for private windows since they will never be autosave or window sessions
if (!Utils.isPrivateWindow(window))
	window.gBrowser.ownerDocument.watch("title", this.updateTitlebar);
window.gBrowser.updateTitlebar();
```

After opening a window session, then closing the window:
```
TypeError: window.gBrowser.ownerDocument.unwatch is not a function
removeEventsObservers@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/bootstrap.js -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/browserWindowOverlay.js:855:4
onUnload@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/bootstrap.js -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/browserWindowOverlay.js:789:5
exports.loadBrowserWindow/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/bootstrap.js -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/browserWindowOverlay.js:1883:23
callback@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/bootstrap.js -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/unload.js:82:7
unloader@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/bootstrap.js -> jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/unload.js:89:7
  unload.js:91
	unloader jar:file:///Users/elhem/Library/Application%20Support/Waterfox/Profiles/fhzo84dk.test%20TST/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/unload.js:91:17
```

**Comment by hawkeye116477** [comment]
`If so, is it possible it could be made to work again in Waterfox, or will the Session Manager addon need to be rewritten to use another method?`
That method was removed, because was breaking some websites like `mlb.com`, so Session Manager needs to be rewritten to use another method or just add polyfill to it, just like Moonchild Productions did for S4E (https://github.com/MoonchildProductions/UXP/commit/ff881bdb6795e0f307b93919f98f454bedde4bb6).

**Comment by ElhemEnohpi** [comment]
Thanks for the info. I'll try and see if I have any luck modifying Session Manager to work without `.watch`.

On the other hand, since maximum compatibility with legacy addons (including popular but abandoned ones like Session Manager) seems to be a goal of Waterfox Classic, maybe a fix could be incorporated into the browser? If it was only available to addons and not web pages, would that solve the problem? It looks like there's some relevant info here: https://github.com/MoonchildProductions/UXP/issues/1261 though I don't completely understand it...

**Comment by hawkeye116477** [comment]
`If it was only available to addons and not web pages, would that solve the problem? `
Yes, maybe @MrAlex94 could do that.

**Comment by carllapa** [comment]
Any news on this issue? Session Manager is key for my workflow and I'm stuck with and outdated version (56.2.14) of WF in order to be able to use it.

I've commented on the topic here: [Session Manager extension broke after updating from 56.2.14 to this version, under Windows 7 x64](https://www.reddit.com/r/waterfox/comments/dmkrxs/waterfox_201910_release_the_next_version_of/fa1wy66).

**Comment by hawkeye116477** [comment]
@carllapa Maybe try https://github.com/Ulf3000/sessionBuddy.

**Comment by carllapa** [comment]
Thank you @hawkeye116477 , I'll give it a try!
Is it possible to import my current Session Manager already stored sessions?
I've a lot and I refuse to lose them :(

**Comment by ElhemEnohpi** [comment]
@carllapa , I feel your pain, losing Session Manager would be a disaster for me.

You can't import Session Manager sessions to SessionBuddy. SessionBuddy is very simple and not comparable to Session Manager. Also, you really shouldn't use Waterfox 56.2.14, it has serious security vulnerabilities.

I'm using Session Manager with the latest Waterfox Classic, with a small change to the source code. It doesn't fix it completely - you won't see the name of window sessions in the window title anymore, but you can still still hover over the Session Manager toolbar icon to see them.

In order to work around this Waterfox issue, you can modify the source code of Session Manager like this:

1. Go to the Classic Addons Archive and find Session Manager
2. Right click on the "install" button and save the Session Manager .xpi file: `session_manager-0.8.1.13-fx+sm.xpi`
2. Change the extension to .zip and unzip it.
4. Edit the file `packages/browserWindowOverlay.js`
5. Find and comment out these lines, like this, and save it:

```
//if (!Utils.isPrivateWindow(window))
//	window.gBrowser.ownerDocument.watch("title", this.updateTitlebar);
//window.gBrowser.updateTitlebar();
```
and
```
// window.gBrowser.ownerDocument.unwatch("title");
```

6. Zip all the contents of the main folder (not the folder itself) back into a file
7. Rename the file to e.g. `session_manager-0.8.1.13-fx+sm+wf.xpi`
8. Drop it on a Waterfox window to install it.

From the above comments, there should be a way to fix it completely, but I haven't had time to try it. Also, it sounds like MrAlex94 should be able to fix the problem in Waterfox; maybe with the new owners/funding, it will be possible.

**Comment by reallyuniquename** [comment]
@ElhemEnohpi
I have a slightly unrelated question. In `Load Session` window, does clicking on a tab entry while holding down the ALT key open that tab in the existing window (as intended by the dev)?

**Comment by carllapa** [comment]
@ElhemEnohpi I've finally got some spare time to test it on a safe environment and it worked like a charm. After some testing I've installed the "fixed" extension on my work environment, updated Waterfox to the latest version and now Session Manager is working as expected.

It's true the session's name got lost in the title bar but you can easily see it hovering the cursor over the Session Manager's floppy icon.

So many thanks for your help and I hope Waterfox keep maintaining compatibility with this old but powerful extensions, for me and my workflow at least Firefox Quantum is totally useless right now without them.

**Comment by Procrust-Ian** [comment]
fyi, in the midst of transferring to new computer, when something --I think the update to the new Waterfox-- wiped out all my Session Manger sessions. After much consternated burrowing I realized that I had saved the contents of my Waterfox user profile folder, and once having found the "Sessions" sub-fplder, could see that they were in there. But how to bring them back I could find no reference to, so I took the chance of simpley copying them over into what was a new user profile (is that what happened with the update?) and changed the name of those which were identical to any already in the new profiile. Restarted windows, loaded Waterfox, and there they were again. What I don't know is if those files from the old profile might have been somewhere on my computer anyway. So very glad I saved that folder! In case this might assist anyone else.
