### ISSUE TITLE
Waterfox spying on you?

### ISSUE THREAD

**Issue by roman6626** [MrAlex94/Waterfox#1264]
Browser pretending to care about your privacy - We’re obsessed with protecting your privacy. That’s why we’ve made Waterfox Private Browsing more powerful than the others., when in fact Waterfox does nothing whatsoever to protect it and actually spies on you almost as much as Firefox https://spyware.neocities.org/articles/waterfox.html (it made 109 unsolicited requests upon my run of it https://digdeeper.neocities.org/images/wfox.png). The more powerful private browsing mode is a sham as well - anyone caring about their privacy will not rely on this but install essential privacy addons, so his deceptive claims are designed to lure in newbies only https://digdeeper.neocities.org/ghost/addons.html Though it has XUL addons support unlike vanilla Firefox, it has all the other flaws and does not even bother to remove much of the spyware. Is this all true?

**Comment by g3ngr33n** [comment]
My opinion :

Every browser will leak every activity made trought it : This is the forever main door for anyone looking to collect data, spy, hack... Private organisation, gov agency, scripts kiddies, blackmailer, robber. Privacy is impossible trought a browser, what you are saying may be right but pointless :

https://en.wikipedia.org/wiki/OSI_model

You are pointing a privacy problem at the layer 7, when it start at the layer 3

Understand having a browser defeat all security/privacy purpose you are trying to achieve.

https://www.cvedetails.com/product/3264/Mozilla-Firefox.html?vendor_id=452

Regarding Waterfox :

https://raw.githubusercontent.com/g3ngr33n/apparmor-profiles-hardened/master/ffisdead.gif

Waterfox classic is still at nowadays, Other are at tomorrow.



I give you few links that should get your attention and energy 

https://wiki.gentoo.org/wiki/Project:Hardened_musl
https://github.com/anthraxx/linux-hardened
https://www.cvedetails.com/product/47/Linux-Linux-Kernel.html?vendor_id=33
https://nosystemd.org/

And this one should definitively get your interest :

https://www.qemu.org

When an application is subject of being insecure, running it inside a qemu image is without any doubt 
the first thing to do.

Hope my post will help you to open your eyes.

Edit : Look at this one https://spyware.neocities.org/articles/vivaldi.html, It consider vivaldi safer than Waterfox.

Vivaldi is closed source, requiring the root access in order to run... The website your are taking source from is a fraud.

**Comment by roman6626** [comment]
How do you feel about this?
https://digdeeper.neocities.org/ghost/browsers.html
Why is this site fraudulent? Is there a lie about different browsers? It is clear that all browsers send information about the user. Only some do more, others less.

**Comment by hawkeye116477** [comment]
@roman6626 The author of this page is not familiar with the subject and writes nonsense or it's controlled fake news.
For example, Waterfox must know which is operating system and version to provides updates.
Self updates can be easily disabled if you don't want it, but Waterfox doesn't add "spyware features" in update. Also it needs to connect to `versioncheck-bg.addons.mozilla.org` to provide updates to extensions, if not then where should it get updates for extensions from, from space?

**Comment by MrAlex94** [comment]
This has come up a few times before. A website with someone who doesn't understand how software development works. Also a complete misuse of the word [spyware](https://dictionary.cambridge.org/dictionary/english/spyware).

> software that collects information about how someone uses the internet, or personal information such as passwords, without the user knowing about it.

I mean they seem to link previous reddit threads, but are extrapolating a lot of points and making up theories. I agree - the way services work aren't always the best, but that's why Waterfox is privacy *focused*, in the sense it's aware and conscious of peoples privacy and tries to have sane defaults rather than being super paranoid about everything - which make the web difficult to use without a lot of features. I've always recommended Tor if someone is paranoid. Waterfox is not here to fill in the role of Tor, which does it much better.

Some more reading:
https://www.reddit.com/r/waterfox/comments/8lrru6/will_you_do_anything_about_waterfoxs_serious/dzien2p/
https://www.reddit.com/r/waterfox/comments/880z4b/what_happened_to_waterfoxs_devotion_to_user/dwh9iqe/

If you want me to go through and counter each point, I will do so. But really at this point, why even bother using a feature rich web browser? Might as well stick to a text browser such as Lynx.

**Comment by roman6626** [comment]
Hi Alex! But in any case, different browsers send different information, and different amounts, and to different servers. And what does it do better - Waterfox or Pale Moon/Basilisk? For some reason, this author selects them in his conclusions.

**Comment by roman6626** [comment]
By the way, you never told me why in the Waterfox MotionMark 1.1 test in the Multiply point the value is always = 1? Basilisk and Pale Moon have no multiprocessing at all. But they always have Multiply values quite large.

**Comment by grahamperrin** [comment]
> Is this all true?

A couple of add-ons that you might like to use in future: 

- [Newsit: Hacker News and Reddit Links](https://addons.mozilla.org/addon/newsit-hnews-and-reddit-links/) 
- [Official Media Bias Fact Check Icon](https://addons.mozilla.org/addon/media-bias-fact-check-icon/)

----

> MotionMark

▶ #1248
