### ISSUE TITLE
Waterfox and Basilisk

### ISSUE THREAD

**Issue by roman6626** [MrAlex94/Waterfox#1290]
Why did the Waterfox developers reject Moonchild proposal to merge the Waterfox and Basilisk browser projects?
Moonchild (M.C. Straver) says this:
"Waterfox Current is what Waterfox has always been: a rebranded rebuild that will use Firefox-release (at arbitrary versions) or -ESR as its base. Waterfox Classic is what Alex attempted on his own after refusing to come on board with UXP in terms of making a fork, and clearly couldn't maintain on his own (which is exactly why I suggested a cooperation for the platform ...) - In fact, if he had come on board with UXP, Basilisk would likely not exist because he would be providing an Australis-type browser with the same features enabled."
Is this true?

**Comment by hawkeye116477** [comment]
If they doesn't wanted to provide support for webextensions, then it was rather good decision.

**Comment by grahamperrin** [comment]
@roman6626 please use Reddit, not GitHub, for discussions. 

https://www.reddit.com/r/waterfox/

Please begin by searching the Waterfox subreddit. You'll find prior discussion of the subject. Use Google, if necessary – https://www.google.com/search?q=site%3Awww.reddit.com%2Fr%2Fwaterfox+%22moonchild%22 and so on. 

----

**GitHub is not a discussion forum**. You might like to subscribe to [Suggestion: Introduce a Discussion tab · Issue #44 · dear-github/dear-github](https://github.com/dear-github/dear-github/issues/44)

**Comment by Polynomial-C** [comment]
I recommend to not merge with Moonchild stuff for two reasons:

- They removed **all** configuration switches to build their browsers against system libraries and thus forcing users to swallow their bundled crap. This is a nightmare from security POV at least on any recent Linux distribution
- Last I've checked you couldn't build their browsers with any recent gcc version. I'd be very surprised if you can finally build their browsers with gcc-8 or newer...

**Comment by smnthermes** [comment]
> This is a nightmare from security POV at least on any recent Linux distribution

@Polynomial-C why is there a different treatment for Firefox? Please stop spreading FUD. 
1. https://www.palemoon.org/releasenotes.shtml
2. https://forum.palemoon.org/viewtopic.php?f=65&t=22270
3. https://forum.palemoon.org/viewtopic.php?f=65&t=22399

**Comment by hawkeye116477** [comment]
They are updating libraries by myself, so it's rather not problem.

**Comment by Polynomial-C** [comment]
@smnthermes: Bundling external libraries is a massive security concern. Even worse if a project disables ALL possibilities to link the software against system libs like Palemoon did in the past and to my knowledge still does. This is a nightmare for all distribution packagers (which I happen to be one)!
Firefox on the other hand still allows linking against external libs even though they still ship bundled libs (which is still a bad thing but not as bad as the Palemoon route).
So I don't spread FUD but just pointing out Palemoon's development/release flaws.

**Comment by hawkeye116477** [comment]
Reason => https://github.com/MoonchildProductions/UXP/issues/1342.

**Comment by Polynomial-C** [comment]
Sorry but all I read there are lame excuses. Yes, sometimes newer lib versions are incompatible as they provide new APIs. But that usually also means that those library upstreams deprecated older versions of their libs and won't add security updates to those old versions. Now we're back at the problem with bundling third party libs. Those bundled versions are usually hopelessly outdated and I sincerely doubt that all those projects who bundle these libs have the skills to recognize and backport all required security fixes for these libs.
Additionally, distribution package maintainers would have to check all packages that come with bundled stuff in order to make sure that they don't come with known security flaws in those bundled third party softwares which is - again - a nightmare to do the more packages are affected by this.

Here is a full writing why Gentoo discourages bundling stuff:
https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
