### ISSUE TITLE
[Classic] Waterfox 2019.10 doesn't detect 2019.12 update

### ISSUE THREAD

**Issue by NebelNidas** [MrAlex94/Waterfox#1323]
If I hadn't checked the blog, I wouldn't have noticed there's an update available. Manual checking in the About dialogue doesn't recognize anything either.

This persists in safe mode and even on fresh installations on other computers, even in different networks with different ISPs. I don't know why this is happening (or which logs I should attach here?), I only know it's not working for anyone here in my area in Bavaria (Germany). The previous updates have all been fine.

**Comment by NebelNidas** [comment]
~~Just tested Waterfox Current, it doesn't work either.~~
I'm stupid, Current 2019.12 didn't release yet! xD

**Comment by MrAlex94** [comment]
2019.12 being pushed to 2019.10 tomorrow. Sorry, Christmas period keeping me plenty busy! All other version have been pushed 2019.12 (except current).

**Comment by lucknaumann** [comment]
I had this problem, too, on both installed and portable versions. I had to manually update. I thought it might have been because I used ShadowFox since I noticed that it prevented some buttons in the Options menu to be selected. I probably should have used an older version of ShadowFox that would be more compatible with Classic/ESR FF. However, since reading this issue, I'm now wondering if there might have been another reason for the lack of Auto Update. FYI: I'm not in Germany.

**Comment by roman6626** [comment]
When will the Waterfox Current 2019.12 update be released? Will this be the final version? When is the finale?

**Comment by lucknaumann** [comment]
@roman6626 
I asked the same question (providing what you mean by 'final version' is stable release branch) and this is what grahamperrin replied with:
[https://github.com/MrAlex94/Waterfox/issues/1272#issuecomment-557446599](url)
[https://waterfox.zulipchat.com/#narrow/stream/214416-general/topic/Waterfox.20Current/near/182180543](url)
So, I don't think there is a scheduled release date for the stable release of Waterfox Current.

**Comment by NebelNidas** [comment]
A Christmas miracle happened today! It finally detected the update on all of my and my friends' computers just around the same time. Can you tell us what caused it, @MrAlex94?
