### ISSUE TITLE
Hi issue when trying import password

### ISSUE THREAD

**Issue by Anonymous-any** [MrAlex94/Waterfox#1398]
Erreur d’analyse XML : entité non définie
Emplacement : chrome://browser/content/migration/migration.xul
Numéro de ligne 30, Colonne 7 :      <radio id="firefox"   label="&importFromFirefox.label;"   accesskey="&importFromFirefox.accesskey;"/>
------^

Regard

**Comment by hawkeye116477** [comment]
Waterfox Current or Classic and which version? Have you installed language pack from AMO or used built-in?

**Comment by MrAlex94** [comment]
As @hawkeye116477 has mentioned this usually happens with a language pack added directly from Mozilla. Start Waterfox in [Safe Mode](http://kb.mozillazine.org/Safe_mode#Starting_Safe_Mode) to fix this.

**Comment by Anonymous-any** [comment]
Hi yes, thank sorry but that not work. The issue is elsewhere.
I made you a picture I'm on Win7x64, Classic with default selected languages as French, I've only installed a dictionary think not linked because disabled too not work:
![1](https://user-images.githubusercontent.com/25174503/74994131-804d8380-544d-11ea-9cbb-53e68ebc38cb.jpg)
Also a big big very big issue with linux 2020.02 version ubuntu/K 18.04 and before who it won't start like you know it and I dunno how we have to solve it as clean way without twist the OS. I did have to back it to 12.19.
Regard

**Comment by hawkeye116477** [comment]
@Anonymous-any Probably that will be fixed in next version, but you can fix this even now, just go to Waterfox Classic/browser/features and replace langpack-fr with that from https://github.com/MrAlex94/Waterfox/raw/3c63d8e98d9b00b056fd7cc9da5e33c40a9afef7/browser/extensions/langpack-fr%40waterfox.xpi.

**Comment by hawkeye116477** [comment]
@Anonymous-any Probably that will be fixed in next version, but you can fix this even now, just go to WaterfoxClassic/browser/features and replace langpack-fr with that from https://github.com/MrAlex94/Waterfox/raw/ab1d07cf438536f8c439c298a60d48e3c2edd468/browser/extensions/langpack-fr%40waterfox.xpi.

**Comment by Anonymous-any** [comment]
@hawkeye116477 thank it's ok for the fix but it's seem only import from IE is available ? ^^ I've got another profile like FF...
![1](https://user-images.githubusercontent.com/25174503/75208437-ee5eb700-577b-11ea-95d6-96ea2d167972.png)
Hep I'm just thinking too, "Import passwords button Waterfox" want to Import all datas bookmark's n' all ??
Br
