### ISSUE TITLE
waterfox is arm64? browser

### ISSUE THREAD

**Issue by mrkapqa** [MrAlex94/Waterfox#1506]
Hello ,

please share a link with a armhf or arm64 version of waterfox if possible.

according to wikipedia 

Waterfox is a arm64 opensource browser, but i have found no download link on the homepage.

thanks

**Comment by hawkeye116477** [comment]
Some time ago was Waterfox for Android (arm64), but now it's not available.

**Comment by mrkapqa** [comment]
hello ,

i am not so interested in Android version, but for desktop use (Waterfox 52? on Rockchip or Raspberry)

Please let me know if there are some building instructions.

**Comment by hawkeye116477** [comment]
@mrkapqa There is no Waterfox for arm64 or armhf for desktop currently. Only I tried the challenge to build for armhf (https://github.com/MrAlex94/Waterfox/issues/1438), but failed.

**Comment by mrkapqa** [comment]
there is a seamonkey 2.6.1 version available in armhf on ubuntu launchpad, 
maybe one can gather info from the buildlog?
this seems a rather ancient version, but i have tried to install the packages one a armbian ubuntu bionic and quite alot of packages very installable.

https://launchpad.net/ubuntu/+source/seamonkey/2.6.1-0ubuntu1/+build/3052865

https://launchpadlibrarian.net/88720368/buildlog_ubuntu-precise-armhf.seamonkey_2.6.1-0ubuntu1_BUILDING.txt.gz

**Comment by mrkapqa** [comment]
i installed this seamonkey2.6.1 armhf on my arm64 box, and it functions well, but some "modern" sites won't load due to missing security tls / ssl standards i suppose.
therefore the need for a more modern, alternative browser to chromium and firefox.
waterfox classic would be a suitable candidate?

**Comment by hawkeye116477** [comment]
`therefore the need for a more modern`

Current => `if you want the latest and greatest the web has to offer, want to use all WebExtensions and a few bootstrap extensions`

Classic => `if you have your browser set up with various NPAPI plugins and bootstrap extensions that have not been updated as WebExtensions or for Waterfox Current`

-------
`maybe one can gather info from the buildlog`

Buildlog contains too less things needed, need too look for `debian.tar.gz/xz` on which there are patches also, because in current state without fixes (patches) build for armhf or arm64 will fail.
