### ISSUE TITLE
website atom bug: duplicate domain info

### ISSUE THREAD

**Issue by steanne** [MrAlex94/Waterfox#1509]
the links in the blog atom feed

https://www.waterfox.net/feed.xml

double up the domain info, leading to invalid links, i.e.

https://www.waterfox.net/www.waterfox.net/blog/9-years-of-waterfox/

**Comment by maxoku** [comment]
Yeah, I just noticed it too when I wanted to subscribe with `Livemark` web-extension in Current. When I reported to add-on site I was told it's invalid URL. Instead of having `https://www.waterfox.net/` everywhere it has only `www.waterfox.net/` without `https://` and that's why it can't manage it properly. I guess it just adds everything started with `www` to `https://www.waterfox.net/ and that's the result.

**Comment by steanne** [comment]
still a problem with today's new post

**Comment by steanne** [comment]
seen fixed for the decennial release announcement.  thank you!
