### ISSUE TITLE
Browser malfunction after opening an external link

### ISSUE THREAD

**Issue by 2BitWizard** [MrAlex94/Waterfox#1540]
**Describe the bug**
When an external Discord link is opened while simultaneously having a Youtube video open in fullscreen mode the browser will "lock" and be unable to switch tabs until it is forcefully closed.

**To Reproduce**
1. Open a Youtube video and put it in fullscreen mode
2. Open a link through the Discord desktop app (on a second display)
3. Revert the video to windowed mode
4. Attempt to switch tabs inside the browser

**Expected behavior**
After the steps shown above the browser should still be able to switch tabs.

**My configuration** 
 - Device: Desktop PC
 - OS: Windows 10
 - Version: Version 2020.04 (64-bit, Current)

**Comment by OnSive** [comment]
Same problem with same configuration here.

Addition to bug report:
The bug is not restricted to discord links. It appears when **opening any URLs**.
Second affect is that the Waterfox process just closes the window but not the process when pushing the exit button (`X`).

**Comment by hawkeye116477** [comment]
`Version 2020.04 `

Classic or Current?

**Comment by Squall-Leonhart** [comment]
can't be classic, otherwise its extension issues.

**Comment by OnSive** [comment]
@hawkeye116477 @Squall-Leonhart 
Waterfox Current

**Comment by 2BitWizard** [comment]
> 
> 
> `Version 2020.04 `
> 
> Classic or Current?

I updated the post, it's Current version
@hawkeye116477

**Comment by BreBat** [comment]
Issue still exists in 2020.06. I've been experiencing this since 2020.03. 

It should also be noted that this isn't limited to youtube. It seems that any full-screen video player will allow this bug to trigger (vimeo, dailymotion, YT...) Interestingly, attempting this in fullscreen mode on a regular page (not a video) will _not_ trigger the bug.

**Comment by baritzu** [comment]
I also have this issue. Doesn't have to be Discord, it did the same thing when I middle clicked a recommendation at the end of a video.

**Comment by BreBat** [comment]
Still present in 2020.07. I've also found the link does not need to be external. Pressing ctrl+t to open a new tab while in a fullscreen video will trigger the bug.

**Comment by not-nocturnal** [comment]
Still present in current 2020.09. 
Haven't seen it mentioned, but the behavior only happens when the new tab is opened in the same waterfox window as the fullscreen video. Furthermore, other windows are still usable after triggering the bug (though it does seem to noticeably impact performance across all windows until waterfox is restarted).

When closing waterfox after triggering the bug, the process will stick around for a few minutes before crashing.

Edit: also thought I'd mention it also maxes out a cpu thread until the browser is restarted, even if the window containing the glitched tab is fully closed.

**Comment by kriskog** [comment]
Fixed in latest current release. 🚀
