### ISSUE TITLE
[Current] Ecosia not listed as a search engine

### ISSUE THREAD

**Issue by colorworm** [MrAlex94/Waterfox#1554]
**Describe the bug**

Unlike Waterfox Classic, there is currently no option to search the web using Ecosia on Waterfox Current.

**To Reproduce**

1. Click on search bar.
2. An option for searching with Ecosia is not listed.

**Expected behavior**

Ecosia should be listed as an option when clicking on the search bar. Additionally the URL of the search should have the form:
 "https://www.ecosia.org/search?tt=waterfox&q=" + Query
where Query is a string variable.

**My configuration** 
 - Device: PC 
 - OS: Windows 7 
 - Version: Current 2020.04

**Comment by timur-g** [comment]
Ecosia is using Microsoft search, doesn't have it's own index.  Yahoo and DuckDuckGo also have a ‘syndication agreement’ with Bing. And giants' search results are biased lately. Which is easy because it's just a couple of them. 
Qwant.com is in Current and can be added to Classic with legacy Add to Search bar addon.

**Comment by MrAlex94** [comment]
This has been rectified and is in G4.
