### ISSUE TITLE
macOS: WF Classic 2020.06 tab crashes when saving as PDF and volume has space in the name (again)

### ISSUE THREAD

**Issue by ElhemEnohpi** [MrAlex94/Waterfox#1629]
**Describe the bug**

Saving a web page as a PDF via  File>Print causes the tab to crash if the destination volume has a space in its name. Same behaviour that was fixed in bug #1123 but is back again since at least 2020.05.

**To Reproduce**
1. Go to any web page
2. Choose 'Print' from the 'File' menu, or press command-P
3. From the popup menu at the lower left, choose "Save as PDF"
4. Choose a folder on a volume that has a space in the volume name. It can be a hard drive, USB stick, or mounted DMG image.
5. Click 'Save'

**Expected behavior**
A PDF version of the web page is saved to the destination folder, just as it is in Waterfox Classic 2020.03

**Actual behavior**
"Gah. Your tab just crashed." No PDF file is saved.

**My configuration** 
 - Device: MacBook
 - OS: macOS Mojave 10.14.6
 - Version: Classic 2020.06

**Comment by rtgilbert** [comment]
Recently upgraded from 2020.03 and began experiencing the same issue/crash:
MacBookPro8,2, BootROM 87.0.0.0.0, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 1.69f4
Mac OS X 10.13.6 (17G10021)
Report Version:        12
Anonymous UUID:        829538C3-063B-6349-AA71-DE8049374ACE

Process:               plugin-container [23145]
Path:                  /Applications/Browsers & Email/Waterfox Classic.app/Contents/MacOS/plugin-container.app/Contents/MacOS/plugin-container
Identifier:            org.mozilla.plugincontainer
Version:               1.0
Code Type:             X86-64 (Native)
Parent Process:        waterfox [18731]
Responsible:           plugin-container [23145]

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[30]'
terminating with uncaught exception of type NSException

Haven't tried 2020.07, may roll back to 2020.03

**Comment by tmkk** [comment]
It seems `file://` scheme path string is passed to `nsPrintSettingsX::SetToFileName` fucntion when e10s is enabled, and fails to create a valid `NSURL` object in the function. This patch will solve the issue:
```diff
--- widget/cocoa/nsPrintSettingsX.mm.orig	2020-07-04 16:49:04.000000000 +0900
+++ widget/cocoa/nsPrintSettingsX.mm	2020-07-04 17:08:12.000000000 +0900
@@ -337,8 +337,13 @@ nsPrintSettingsX::SetToFileName(const ch
   NSMutableDictionary* printInfoDict = [mPrintInfo dictionary];
   nsString filename = nsDependentString(aToFileName);
 
-  NSURL* jobSavingURL =
-      [NSURL fileURLWithPath: nsCocoaUtils::ToNSString(filename)];
+  NSString *pathOrURL = nsCocoaUtils::ToNSString(filename);
+  NSURL* jobSavingURL;
+  if ([pathOrURL hasPrefix: @"file://"]) {
+    jobSavingURL = [NSURL URLWithString: pathOrURL];
+  } else {
+    jobSavingURL = [NSURL fileURLWithPath: pathOrURL];
+  }
   if (jobSavingURL) {
     [printInfoDict setObject: NSPrintSaveJob forKey: NSPrintJobDisposition];
     [printInfoDict setObject: jobSavingURL forKey: NSPrintJobSavingURL];
```

**Comment by rtgilbert** [comment]
Good timing, seems I found the original report on Bugzilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1467582) and a more involved patch (https://hg.mozilla.org/integration/mozilla-inbound/rev/cf8f41907eb84464dd816b69cf731bb0b880edcc).

For the moment I've rolled back to 2020.03.1.  Will try to remember to update this after I get around to doing the patch.
Thanks

**Comment by CL-Jeremy** [comment]
Can you please try [2020.07.2](https://cdn.waterfox.net/releases/osx64/installer/Waterfox%20Classic%202020.07.2%20Setup.dmg)? It seems to be related to the fact that `MACOS_DEPLOYMENT_TARGET` gets set higher during the build process, unintentionally, than what the build script specifies. According to that bug report, there seems to be a change in behavior when development target is set to 10.9 rather than the previous 10.7.

I myself have tested this on 10.8, 10.10 and 10.15. No crashes. Of course, this doesn't mean the patch you referred to need not be merged.

**Comment by MrAlex94** [comment]
I second what @CL-Jeremy has said. I finally have a 10.9 VM up and running, and 2020.07.2 seems to not crash when printing to PDF on a named volume (I'm hoping `Macintosh HD` counts). Please re-open if I am mistaken :-)

**Comment by ElhemEnohpi** [comment]
Seems to be working again on 10.14 Mojave with 2020.07.2, thanks!
