### ISSUE TITLE
Unable to run either Classic or Current versions of Waterfox on openSUSE LEAP 15.1 and 15.2

### ISSUE THREAD

**Issue by broadstairs** [MrAlex94/Waterfox#1631]
Everytime I start waterfox classic or current (latest versions) it fails with an error because the correct version of libc is not installed. This makes waterfox unusable on Leap, the last version which does run is 2020.03. Can you please fix this so I can run Leap without having to make massive changes to the software which is installed by default on a stable system.

**Comment by hawkeye116477** [comment]
As written on website, glibc 2.28 is required, so it's not a bug, it's a feature...

However, you have also unofficial packages => https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage, you can choose AppImage or RPM/repository.

**Comment by broadstairs** [comment]
Well that's all very well but I normally make it a rule not to install anything from anywhere which is unofficial. I simply do not see why you require such a high level of glibc when most stable distros do not use the latest level. This make it difficult to use Waterfox without modifying a stable distro or use an unofficial package which cannot be guaranteed. I think this is a short sighted view of things.

**Comment by hawkeye116477** [comment]
> Well that's all very well but I normally make it a rule not to install anything from anywhere which is unofficial.

All used source files are available (some on GitHub, some on OBS, on service file you'll see sources), so you can always look, if you are afraid of. I'm also always uses [service](https://build.opensuse.org/package/view_file/home:hawkeye116477:waterfox/waterfox-classic-kpe/_service?expand=1) file to make downloading source from official GitHub, so you don't need to download tarball and look what it's inside. Waterfox Current AppImage is also compiled with PGO+LTO, so can work little better than that in official package. Anyway, that's your choice.

> I simply do not see why you require such a high level of glibc when most stable distros do not use the latest level

It's because MrAlex compiling on some newer distro and unfortunately backward compatibility on Linux isn't working well.
In turn, I have the power of openSUSE Build Service at my disposal, so I can use many VMs and distributions.

**Comment by broadstairs** [comment]
Well I understand what he is doing but not sure why. To my mind I'd want the maximum exposure of the product so I would try to compile it on one of the long term support distros which does not have leading edge products installed. The chances of it not working with a higher level is certainly not large in my experience, but having to either use unofficial locations to download or compiling locally means you miss out on easily updating the product as you have to hunt out the newest version rather than relying on the products own distribution method and you can more easily miss out on security updates.

**Comment by ilu33** [comment]
It's not just Suse Leap, its also 'buntu LTS and Debian stretch - half the Linux eco system. And that's the conservative part of Linux users, that's exactly the people waterfox appeals to. Nobody understands this. There have been several issues about it, see f.e. here https://github.com/MrAlex94/Waterfox/issues/1356, https://github.com/MrAlex94/Waterfox/issues/1393, https://github.com/MrAlex94/Waterfox/issues/1393, https://github.com/MrAlex94/Waterfox/issues/1128 ... It was fixed for waterfox 20.03 but bad again starting with 20.04.

This is not a problem of backwards compatibility, it is a problem of not understanding how Linux works. Minimum dependencies on Linux are not meant to be set randomly but according to what minimum version is needed. This library version is certainly not needed, as every new firefox version clearly demonstrates.

@hawkeye116477 since you are commenting here: Your -kpe package has the same dependecy on glibc 2.27. Did you compile from source? If yes can you document your build process somewhere? *fox is probably not the easiest thing to compile from source.

**Comment by hawkeye116477** [comment]
> since you are commenting here: Did you compile from source? If yes can you document your build process somewhere? *fox is probably not the easiest thing to compile from source.

You can see how I do that on https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/blob/master/waterfox-current-kpe/rules.

> Your -kpe package has the same dependecy on glibc 2.27.

That depends for what distro it is, for example for Ubuntu 16.04 required version is 2.18.
