### ISSUE TITLE
Feature Request: disable 'check for update' option

### ISSUE THREAD

**Issue by danrobi11** [MrAlex94/Waterfox#1700]
I havent find a way to totally disable checking for update. What I see its rather 'update automatically' or 'check for updates but let me choose to install them' Nothing letting me disable 'checking for update' I dont need waterfox to check for update, I get new release from rss feed. I also Noticed it was checking often so really dont need that.

**Comment by hawkeye116477** [comment]
@danrobi11 You forgot to mention that's for Waterfox Current.

**Comment by XenHat** [comment]
@danrobi11 Compile Waterfox locally with this config flag: `--disable-updater`.
Alternatively, override the DNS for the update check url.
Globally disabling update of a web browser that is not part of a package manager is very dangerous, but possible.

**Comment by alltagshack** [comment]
+1

I am missing this feature, too! let's talk about compromise:

- at least, what is good, I can prevent an automatic update. I got trubble with it, because `pacaur` (a system package manager from archlinux)
- the hint window every time at startup is annoying: only an icon change would be a compromise for me instead of the window
- traffic and search for an update: why should it not be possible to specify in the GUI the days in which updates are searched for or -1 for "never"?

**Comment by alltagshack** [comment]
Hi. I am still missing this feature or any workaround without re-compilation or a system-wide DNS hack. My hints about:config seams out of date and less documented :-S
