### ISSUE TITLE
Feature Request:   Dump Firefox Sync and replace with other options

### ISSUE THREAD

**Issue by tcreek** [MrAlex94/Waterfox#1721]
With Mozilla now having issues, and canned a bunch of developers, how about getting rid of  the Firefox Sync and adding others we can use?

Closed Source:
DropBox?
OneDrive?
Asus Cloud?

Open Source:
NextCloud?
Open Media Vault?
 Ceph?
...and others.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Hopefully Firefox Sync will work a long time. You can always [fork and deploy](https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html) your own synchronization server.

**Comment by MrAlex94** [comment]
Firefox Sync is open source and can be self hosted so it seems silly to remove it. Worst case if Mozilla shuts it down it can be hosted elsewhere. We are looking into having a paid version, to cover the costs of hosting it for users, but at the moment the value proposition for offering the same service as Firefox Sync already is pointless, so we're looking into what else users would benefit from (happily take any suggestions of what you'd considering supplementing the service with).

Marking this as closed, since Firefox Sync is an invaluable service, open source and can be self hosted.

**Comment by tcreek** [comment]
Mozilla has been losing some credibility also. and people do not trust their sync, so many do not see it as "valuable"

**Comment by MrAlex94** [comment]
User data in Sync is in a "black box". Mozilla can't do anything with the data and it's only accessible by the user (unless this has changed?). The source code can also be audited and is there for anyone to look at. I don't see any reason not to use it?

**Comment by tcreek** [comment]
Thanks for the insight. Many Privacy sites are reporting Mozilla Sync as a privacy issue
