### ISSUE TITLE
Waterfox Third Generation firefox.settings.services.mozilla.com

### ISSUE THREAD

**Issue by schoolprivacy** [MrAlex94/Waterfox#1851]
Water Third Generation = phones home to firefox.settings.services.mozilla.com everytime you start the browser.

You can disable this in firefox, editting the onma.ja file.  This is not possible with Waterfox, i can not find the setting anywhere.

Waterfox Classic - does not make the connection everytime you start up.

**Comment by ghost** [comment]
This isn't the only one, there's a bunch more, it's not fullproof as it sounded, perhaps these things are burried so deep that aren't exactly obvious.

I learned about Waterfox only a few weeks ago, I just wasn't looking before I guess, I kept tweaking Firefox on my own for many years, I kinda got fed up and wanted to build my own version, Waterfox fits this right on, but I wouldn't say perfectly. I'd remove cloud sync, as well as other components and make things even more strict because I just don't need it, most of these are gimmicks to me and lazy conveniences that only promotes a user expecting everything to be done for them, including custom defaults so I don't have to spend a whole freaking afternoon configuring about:config - Many configs are still the bad defaults in Waterfox, kinda disappointed a bit there.

**Comment by InvisibleManX** [comment]
@schoolprivacy 
> Water Third Generation = phones home to firefox.settings.services.mozilla.com everytime you start the browser.
> 
> You can disable this in firefox, editting the onma.ja file. This is not possible with Waterfox, i can not find the setting anywhere.
> 
> Waterfox Classic - does not make the connection everytime you start up.

Are you sure it's gone? 
In Waterfox Current there's a file "omni.ja" inside its installation folder (which can be opened by WinRar), 
and inside I found a file "greprefs.js" and it had the setting `firefox.settings.services.mozilla.com`

**Comment by ilikenwf** [comment]
There's nothing like this on my install under Linux.

**Comment by ilikenwf** [comment]
IceCat fixed it with this:

https://git.savannah.gnu.org/cgit/gnuzilla.git/tree/data/patches/disable-settings-services.patch

**Comment by InvisibleManX** [comment]
@ilikenwf It's already disabled in G3.0.2 Waterfox

**Comment by ilikenwf** [comment]
Good to know.

**Comment by BugFixesAndPerformanceImprovements** [comment]
As of version G3.1.0 connections to `firefox.settings.services.mozilla.com` still occurs.

**Comment by MrAlex94** [comment]
I've done my best to limit the amount of connections done to the settings sync service. Unfortunately when blocking it completely, it's broken some internal pages (such as about:newtab). It's also needed for things such as extension blocklists.

For the next major milestone we've been dissecting what calls it makes and how we can try have an offline-first approach. One idea is to have a proxy in between to anonymise each request - but will see how much that affects performance.
