### ISSUE TITLE
"Gah. Your tab just crashed" from certain site since the classic 2021.01

### ISSUE THREAD

**Issue by e1q3z9c7** [MrAlex94/Waterfox#1923]
It's ok with 2020.10. If I turn javascript off in 2021.01, a small part of the site can be displayed without crash. 
Since It needs to login to reproduce the crash, I attached the source code of the site.
[code.txt](https://github.com/MrAlex94/Waterfox/files/5891694/code.txt)

(sorry I don't know the formal report pattern, hope it's helped)

**Comment by Squall-Leonhart** [comment]
you didn't mention the site.

**Comment by e1q3z9c7** [comment]
https://tw.pairs.lv/#/search/grid/1 it needs to be register by facebook in order to browse

**Comment by berriesandnuts** [comment]
Ahh yes!  I've been experiencing seemingly random shutdowns of the browser recently since I've upgraded to G3.0.2.  I'm on the most recent Windows update also.   In fact, the most recent occurance was here...   https://www.kohls.com/product/prd-3014600/izod-leon-mens-casual-ankle-boots.jsp
I clicked on the link, and the browser shut down.

**Comment by notpushkin** [comment]
I'm experiencing tab crashes every time I try to play a video. I'm on 2020.10 Current right now (can't get myself to update to G3 just yet).

**Comment by Squall-Leonhart** [comment]
start your own new bugs, this is a classic issue, which is almost entirely seperate source code to newer.
