### ISSUE TITLE
Github Globe Freezes Classic on os x Lion 10.7.5

### ISSUE THREAD

**Issue by pjpreilly** [MrAlex94/Waterfox#1927]
The github.com welcome page with the globe (signed out) freezes the Classic browser on os x 10.7.5.

![Screenshot 2021-01-31 at 5 54 36 PM](https://user-images.githubusercontent.com/10430084/106400684-e4aeec00-63ed-11eb-8233-415279610c09.png)

**Comment by pjpreilly** [comment]
Maybe  @aeiouaeiouaeiouaeiouaeiouaeiou   can add some insight here?
It's not the hardware since this runs fine on Waterfox Classic on Ubuntu on this machine....

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
What does the `about:support` page show about WebGL graphics on both systems?

I checked on virtual machine without 3D graphics support, that page tries to load a **huge** MP4 file ([don't click](https://github.githubassets.com/images/modules/site/home/globe-900.h264.mp4)) in case of WebGL processing error. It was a bit strange decision to add that file because even on newer systems it eats up a lot of resources.

![2021-02-01_08-54-00](https://user-images.githubusercontent.com/69355938/106421822-7cecb580-646e-11eb-9e93-19705bb66658.png)

**Comment by pjpreilly** [comment]
Here's the linux info....
![WwbGL WF Classic Linux](https://user-images.githubusercontent.com/10430084/106494520-88e57100-6488-11eb-9fea-ca8fb96dffce.png)

**Comment by pjpreilly** [comment]
.. & this is on os x 10.7.5 Lion...
![WebGL WF Classic Lion](https://user-images.githubusercontent.com/10430084/106497117-a7993700-648b-11eb-98a2-7b38284e0595.png)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Tested on other UXP and Firefox forks, seems Apple's video driver is too old for this sort of thing.
