### ISSUE TITLE
WF Classic unable to display site

### ISSUE THREAD

**Issue by Gebarx** [MrAlex94/Waterfox#1937]
WF Classic 2021.01.1 unable to display site [https://www.translatum.gr/forum/](https://www.translatum.gr/forum/) shows blank page. Same with add-ons disabled. Root site [https://www.translatum.gr/forum/](https://www.translatum.gr/) displays OK. The forum displays fine in all other browsers (Firefox, Opera, Chrome, Edge), even in WF Current.

**Comment by Squall-Leonhart** [comment]
requires an unsupported polyfill that is never coming to classic.

**Comment by roman6626** [comment]
There is no secret or miracle here. Waterfox Classic works worse and worse in the modern web. It is technically outdated. And soon this version will just die. There will be only Waterfox Current - practically, the same Firefox.

**Comment by hawkeye116477** [comment]
Appears that problem is with this:
```
if (window.matchMedia("(prefers-color-scheme: dark)").media === "not all") {
    document.documentElement.style.display = "none";
    document.head.insertAdjacentHTML(
        "beforeend",
        '<link rel="stylesheet" href="https://www.translatum.gr/forum/Themes/CustomSunRise/css/sunrise.css?fin20" onload="document.documentElement.style.display =">'
        );
    }
```
In short problem is that Waterfox Classic doesn't support `prefers-color-scheme`, so content is hidden, because webmaster made a bug in code (onload in css is wrong).

If you have uBO or AdGuard, then you can add to them => `translatum.gr##+js(remove-attr, style, html[style="display: none;"])` to fix that.

Alternative solution:
Create userscript in Violentmonkey/Greasemonkey/Tampermonkey
```
// ==UserScript==
// @name        Fix translatum.gr
// @namespace   Violentmonkey Scripts
// @match       https://www.translatum.gr/forum/
// @grant       none
// @version     1.0
// @author      -
// @description 2/8/2021, 1:08:41 PM
// @run-at document-idle
// ==/UserScript==

document.documentElement.style.display = "";
```
