### ISSUE TITLE
Waterfox Classic is not possible to post a comment on vk.com and other similar

### ISSUE THREAD

**Issue by ruboard** [MrAlex94/Waterfox#1956]
Starting with Waterfox Classic 2020.12, it is not possible to post a comment on https://vk.com Waterfox Classic 2020.10 works fine
the submit comment button is not active
https://images2.imagebam.com/22/a4/d7/5902c21370619737.JPG

**Comment by ruboard** [comment]
it turned out the bug is observed in win7 in win10 everything is ok. 
waterfox now relies on libraries from win10? -This is very very bad.

**Comment by ruboard** [comment]
replacing two dll from 2020.10 solves the problem
vcruntime140.dll
ucrtbase.dll

**Comment by Squall-Leonhart** [comment]
neither of these should be shipped with a windows application, they should be installed via windows updates or the vcredist package.

> **Local deployment**
> 
> Local deployment of the Universal CRT is supported, but not recommended for both performance and security reasons. The DLLs for local deployment are included as part of the Windows SDK, in the Windows Kits\10\Redist\ucrt\DLLs subdirectory, by computer architecture. The DLLs required include ucrtbase.dll and a set of APISet forwarder DLLs named api-ms-win-*.dll. The set of DLLs required on each operating system varies. It's highly recommended that you include all of the DLLs when you deploy locally.
> 
> There are two restrictions on local deployment to be aware of:
> 
>     On Windows 10, the Universal CRT in the system directory is always used, even if an application includes an application-local copy of the Universal CRT. It's true even when the local copy is newer, because the Universal CRT is a core operating system component on Windows 10.
> 
>     On versions of Windows before Windows 8, the Universal CRT can't be packaged locally with a plugin, if it's located in a directory other than the directory of the main app executable. The APISet forwarder DLLs are unable to resolve the ucrtbase.dll successfully in this case. Some recommended alternative solutions include:
>         Statically link the Universal CRT,
>         Centrally deploy the Universal CRT, or
>         Place the Universal CRT files in the same directory as the app.


replacing runtime files shouldn't fix anything to do with web content, these are function export libraries and if anything were broken or not working in them the browser wouldn't even start or crash.

Your issue should not be caused by either of the files.

It definitely cannot be caused by  vcruntime140.dll because there hasn't been a version change.

**Comment by ruboard** [comment]
nevertheless, it was the replacement of these two libraries that solved the problem
they are just copied from the system32 folder
installed package from here https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by Squall-Leonhart** [comment]
It wasn't solved, only worked around.

**Comment by ruboard** [comment]
Squall-Leonhart not related to the developer, do not write.
I didn't take the problem from the sky

**Comment by Squall-Leonhart** [comment]
Learn how dynamic link libraries work, and fix your computer

No repro.

/closed

**Comment by ruboard** [comment]
Squall-Leonhart "/closed"
are you a moderator here?
or not find another place to flood?
the bug has long been confirmed by a dozen people at least, three months ago. 
smart guy found, moron

**Comment by Squall-Leonhart** [comment]
>  the bug has long been confirmed by a dozen people at least, three months ago.

no it hasn't.

Flaws in your theory

1> The vcruntime140.dll is the same binary version between 2020.10 and 2021.1 and 2, just signed differently  (so vcruntime cannot  cause your problem)
2>   ucrtbase.dll is the same used in current firefox, which also works just fine there (and 10.19042.789+10.18362.0 applied from a windows 10 install also does not display the issue anymore)

I'm testing some things though, and if  im right the issue will be due to the build configuration or source libs.

I have ruled out the files themselves as firefox and palemoon work on that site.
at the same time Waterfox 2020.10 and 2021.2 work fine with ucrtbase.dll 10.19043.789 and 10.18362.

My working theory is that the version of the MSVC libraries MrAlex is building with has a bug that is worked around in later DLL's but is fixed or not present in the libraries Mozilla is using to build with.

@hawkeye116477 @MrAlex94 can you check the dependency chain for updates or known issues, the things relevant to the UCRT in particular.

Attached are the 2 newer ucrtbase files that do not display the issue.
[UCRTBase.zip](https://github.com/MrAlex94/Waterfox/files/6033965/UCRTBase.zip)

not present in 17763.132 either

**Comment by Squall-Leonhart** [comment]
@ruboard 

issue is particular to Waterfox's libs (or code) and the ucrt dll in combination, this error only occurs with the specific combination of UCRT libs(or compiler optimizations) that waterfox is built with and the 17132.12 dll. the VCruntime is irrelevant and not a factor, I believe  both dll's are a victim considering the same dll's in Firefox do not log any error and work fine.

The bug involves regular expressions failing when parsing the sites stories

Attached is a screenshot of the site loaded with 10586.15
![image](https://user-images.githubusercontent.com/1098176/108968826-620c0a80-76d5-11eb-84da-7b18dfd2f3b5.png)

The site loaded with the system ucrt version
![image](https://user-images.githubusercontent.com/1098176/108968987-95e73000-76d5-11eb-933d-77da535ca06f.png)

The site loaded with 17134.12 (note the error)
![image](https://user-images.githubusercontent.com/1098176/108971382-5c62f480-76d6-11eb-897f-8041e44da509.png)

The site loaded with 17763.132
![image](https://user-images.githubusercontent.com/1098176/108971777-c54a6c80-76d6-11eb-84ea-4f7f8d47a409.png)

The same issue would be present for any user running windows 10 1803.

Meanwhile, the site in firefox with 17134.12
![image](https://user-images.githubusercontent.com/1098176/108973015-055e1f00-76d8-11eb-9851-fc05265a11ce.png)

@MrAlex94  the issue will not manifest in 10 (except for 1803 updates prior to 191) because the bundled ucrtbase is never used, 10 always loads the system ucrtbase.

**Comment by ruboard** [comment]
I do not understand what you write, I am not a developer or a programmer.
this problem has been discussed at the Russian forum since October. it turned out that win10x64 users have no problem. and only applies to win7x64.
there is also an explanation of this:
https://www.waterfox.net/blog/waterfox-2021.01-release/?new
https://www.waterfox.net/blog/waterfox-2021.01-release/?new

**Comment by Squall-Leonhart** [comment]
>  this problem has been discussed at the Russian forum since October. it turned out that win10x64 users have no problem. and only applies to win7x64.

Needs to be brought up here to get attention :(

> I do not understand what you write, I am not a developer or a programmer.

Thats ok, the developers will i hope.

Just note that before Windows 10 17164.191, this issue would appear on windows 10 as well, whatever waterfox is doing is broken prior to UCRTBase 17134.191 (broken atleast till 17134.165)

Screenshot of it working with ucrtbase 17134.191
![image](https://user-images.githubusercontent.com/1098176/108976589-c92cbd80-76db-11eb-815d-0acb26fb08e9.png)


the UCRT change for 17134.191 is

> Improves the ability of the Universal CRT Ctype family of functions to handle EOF as valid input.

**Comment by Squall-Leonhart** [comment]
Just a reminder to @mralex94, please update the toolchain and packaged runtimes to 17763 or newer before building and releasing 2020.3+

**Comment by Squall-Leonhart** [comment]
This has been fixed both by updating the toolchain, as well as the implementation of ASCIIAlpha in 6e7af44c936f803ccf10fb727e4ed5651249d622
