### ISSUE TITLE
Waterfox classic and Polly

### ISSUE THREAD

**Issue by ilu33** [MrAlex94/Waterfox#1958]
The release notes mention, that the Polly addon was added and I can see its icon. From other comments I understand that it was meant to fix the polyfill issues f.e. github and reddit have.

I see 2 problems with this:

1. The github repo https://github.com/zakius/Polly is empty. If there ever was anything (and I asume there was) this means that the history got pruned, which - under normal circumstances - is something only github can do. So what happened there exactly? I'm guessing that this is not the fault of @MrAlex94 but it's a mess nonetheless. @MrAlex94, why did you not clone zakius repo so we could still see the content? Or did you clone and it got removed?

2. Whoever uses classic has to know that there is no way to make all sites work with it. As a classic user you just have to accept this and I certainly do. If I wanted to fix polyfill issues I could install polly myself. But forcibly adding it to the code is certainly controversial, especially if it is done without any prior discussion or announcement (as far as I can see). This issue is made worse by the situation explained above under 1.

**Comment by Squall-Leonhart** [comment]
my best guess is Mozilla abused DMCA to have polly removed.

**Comment by KandiPanda** [comment]
As far as I can tell, the old repo was deleted, and a new one was created in its place (I see "Created 1 repository - zakius/Polly" for Feb 20, 2021 on zakius' github profile.

I think I found the fork tree left behind by the original repo by searching for forks of it on DuckDuckGo though, the (fork of a) fork with the most recent version in its releases page seems to be https://github.com/kiyn/Polly with v1.9 from Dec 9, 2020, (but added sometime before an xpi file was added to the 1.9 release). Appears that copying the contents of the folder inside the "source" zip into another zip and renaming the new zip to a .xpi extension may let it install, though? (IIRC, the more recent 1.10/1.11/1.12 releases were just something to do with letting it auto-update rather than adding any polyfills, but I never downloaded/installed those, so I can't help with that.)

Maybe someone can revive it from the fork tree?
