### ISSUE TITLE
[G3][Feature request] Manual dark mode setting

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [MrAlex94/Waterfox#1996]
It would be nice to implement the dark mode toggle in browser settings because some Linux distros and pre-Mojave macs do not support automatic theme switching.

![wf1](https://user-images.githubusercontent.com/69355938/111545762-98deb900-8787-11eb-90e9-84a4268adc33.gif)

**Comment by MrAlex94** [comment]
Is this any different to setting the theme to `Abyss`?

**Comment by jabcreations** [comment]
It looks like implementing Dark Mode support for websites would be simple:
https://stackoverflow.com/a/51336913/606371

Test site (use Chrome unfortunately or Safari):
https://www.jabcreations.com/blog/

I figured out how to force Firefox 71+ to enable dark mode on sites that natively support it:
https://www.fixedfirefox.com/blog/

I think this would be a huge bang-for-the-buck so-to-speak. I personally use Stylus to fix sites I frequent since I'm stuck working on my computer 12+ hours every day. Oh - I'm talking about **Waterfox Classic**.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
> 
> 
> Is this any different to setting the theme to `Abyss`?

Simple change of theme does not cause effects on [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS function.

**Comment by MrAlex94** [comment]
I think I see now - so lets say a dark theme is set alongside maybe another preference - we want `prefers-color-scheme` to report whether the system is reporting being in "dark mode" - even if it isn't?

**Comment by jabcreations** [comment]
Some people may have control over their browser though not their operating system. It makes sense to allow people to override locally what they can not globally. One OS install, multiple users and therefore one (or more) profiles per OS user.

**Comment by MrAlex94** [comment]
Forgot to update this! Should be available in about:preferences > General > Languages and Appearance > Dynamic Themes
