### ISSUE TITLE
(Classic) 2021.03 - Multiprocess Crash (fixed by using old AccessibleHandler.dll)

### ISSUE THREAD

**Issue by docrR** [MrAlex94/Waterfox#2023]
Essentially. Forcing multiprocess mode via boolean _**browser.tabs.remote.force-enable**_ crashes the browser after around 2020.10. I observed this on both 7 x64 and 8.1 x64 on two different machines with fresh profiles. I reproduced this on a vm of Windows 10 too, however it isn't patched to the latest patch level. 
There's no crash log in either scenario, just an application has stopped working error. I eventually traced the issue to AccessibleHandler.dll after reading similar issue reports. I dropped in the affected dll from 2020.09 into 2021.03's installation directory and all is working as intended again.

**Comment by Squall-Leonhart** [comment]
This is an issue with your computer, not waterfox.

![image](https://user-images.githubusercontent.com/1098176/114125869-a0365400-993a-11eb-838c-e753ba1ad024.png)

![image](https://user-images.githubusercontent.com/1098176/114125886-aaf0e900-993a-11eb-8c72-f1c52c0531c0.png)

There are no issues running Classic on any  version of Windows that is on top of updates, everyone reporting this has opted to running unpatched since early 2020 resulting in them lacking windows UCRT and other ntos updates, and likely aren't on top of VC14 runtime updates either.

**Comment by Squall-Leonhart** [comment]
Downvote as much as you want, the issue is your own doing,

**Update Windows.**

There is no justifiable reason not to be using ESU updates if you are choosing to remain on Windows 7

**Comment by Squall-Leonhart** [comment]
If you can't fathom that the application works properly for most others but doesn't for yourself, thus is an issue on your machines specific configuration and lack of updates,

please stop using github and leave the internet.

**Comment by AM4Ryzen** [comment]
> 
> 
> If you can't fathom that the application works properly for most others but doesn't for yourself, thus is an issue on your machines specific configuration and lack of updates,
> 
> please stop using github and leave the internet.

Stop being an asshole

Also, I'm not alone https://twitter.com/gitlost

**Comment by Squall-Leonhart** [comment]
Stop doing wrong/dumb/incompetent things and expecting to be supported in doing them.

**Comment by AM4Ryzen** [comment]
> 
> 
> Stop doing wrong/dumb/incompetent things and expecting to be supported in doing them.

Go back to the Steam forums dumbass

**Comment by Squall-Leonhart** [comment]
Also evidence that it works fine in Windows 8.1 x64 as well, since that was cited.

![image](https://user-images.githubusercontent.com/1098176/114487782-87d47b00-9c53-11eb-9d1f-d2eb5932b9fd.png)

![image](https://user-images.githubusercontent.com/1098176/114487806-9327a680-9c53-11eb-8daf-97b8282f19d9.png)

If users run without necessary Windows updates as a choice, Issues happen and this is certifiable User Error and will not be supported by developers anywhere.

**Comment by AM4Ryzen** [comment]
> 
> 
> Also evidence that it works fine in Windows 8.1 x64 as well, since that was cited.
> 
> ![image](https://user-images.githubusercontent.com/1098176/114487782-87d47b00-9c53-11eb-9d1f-d2eb5932b9fd.png)
> 
> ![image](https://user-images.githubusercontent.com/1098176/114487806-9327a680-9c53-11eb-8daf-97b8282f19d9.png)
> 
> If users run without necessary Windows updates as a choice, Issues happen and this is certifiable User Error and will not be supported by developers anywhere.

The browser works fine for me too, but do you see me being an asshole about it?

**Comment by Squall-Leonhart** [comment]
Other reports of the issue exist (had the user searched), and the conclusion was the same.

Refer to https://github.com/MrAlex94/Waterfox/issues/1957#issuecomment-782815012

**Comment by docrR** [comment]
> 
> 
> Other reports of the issue exist (had the user searched), and the conclusion was the same.
> 
> Refer to [#1957 (comment)](https://github.com/MrAlex94/Waterfox/issues/1957#issuecomment-782815012)

The user has in fact searched, considering it isn't my first instinct to start hatcheting away at AccessibleHandler.dll. (I discovered the _solution_, if we're going to call it that found in another issue. Let's call it a temporary mitigation for the sake of discussion). 

I won't comment on the state of ESU updates, but I suppose one can stipulate those of us holding out from 10 have alternate means of patching our systems. (probably by applying esu patches) Nevertheless It's rather bold of you to assume to everyone is in the ESU programme, given the fact there's no legal way to acquire them by normal means. Somehow I doubt Wf Classic has a particularly large enterprise presence, though if I'm mistaken do feel free to cite me there. 

Now putting the pissing contest aside, I propose a compromise that won't end with System1 being sued by Microsoft for suggesting unauthorized use of their ESU programme: 

- At what what patch level did these UCRT/ntos changes land? Are there specific kbs available on Microsoft's update catalogue that come to mind? I was having to force-enable e10s vis boolean on a 2019-04 patched copy of 7 in... you guessed it, April of 2019.
- Bold idea here, but I've been bolder before, so just hear me out: 
Maybe drop a warning when an internal change is considerable enough to disagree with some systems? Rather than vaguely say _**Requires Windows 7 or greater**_ or something to that affect. Maybe list expected dependencies, a minimum suggested patch level, perhaps a gentle reminder to update VC? Throw out that SP1 is expected?

Anyhow, no disrespected toward Mr. Alex or System1 intended. I'm beyond grateful to have G3 and Classic at my disposal.

_You might be interested in the Pale Moon forum btw. There's plenty of hermits there you may enjoy engaging with :)_

**Comment by Squall-Leonhart** [comment]
Your only recourse is to use 2020.10 and stay there or migrate to windows 10 since you appear against using legal gray area software to move beyond the final january 2020 patch.

The last Waterfox version for you that works, works up to kernelbase 6.1.7601.24559, provided by the June 2020 Cumulative update.

Beyond that 6.1.7601.24560 and 6.1.7601.24562 being provided by the September 2020 and November 2020 Cumulative updates.

As to the legality of a user of available esu bypassses

Microsoft has no legal standing to drag anyone using an esu bypass to court, since as far as the law is concerned the product is already paid for and the law protects software users who desire to modify their own software 

Distributors of esu bypass on the other hand are not offered such protection.

**Comment by docrR** [comment]
........Nevertheless. I appreciate everyone's time. While I may agree to disagree, I shall close the issue now.

https://youtu.be/RThMFYBtZLw
