### ISSUE TITLE
Performance Observer didnt work - Waterfox Classic 2021-3/Win7 x64

### ISSUE THREAD

**Issue by Felipefpl** [MrAlex94/Waterfox#2024]
* Implementation and activation of PerformanceObserver. Helps load websites such as GitHub.

This change didnt work as intended, github still displays the msg "GitHub no longer supports this web browser." when you log in plus if i click in the 3 dots to expand a long phrase anywhere nothing happens. Nothing changed.

Github works nicely on firefox, i dont understand why the code that firefox uses to make github work cant be copied/pasted on waterfox since this is done all the time with the changes from ESR. Why that happens?

**Comment by hawkeye116477** [comment]
> This change didnt work as intended, github still displays the msg "GitHub no longer supports this web browser.
> Nothing changed.

Well, typical user maybe didn't notice anything, but console doesn't display message about Performance Observer now. 
Adding labels for example wouldn't work without Performance Observer.
Performance Observer works as intended, but GitHub also needs webcomponents support. Implementing that isn't that easy, especially that Mozilla done most work for Servo, which is disabled on Waterfox Classic. Moonchild has same problem.

If someone used Polly extension should notice that webcomponents Polyfill starting wouldn't be enough, but now Performance Observer is implemented, so that problem is solved now.


> this is done all the time with the changes from ESR

Not always, usually code must be little modified, cuz from 56 to current ESR there are much differences.

------------------------------------------
PS: For GitHub going to `about:config` and setting `dom.webcomponents.enabled` to `true` should be enough, but because :host() and some other things aren't implemented, some another websites may stop working.

**Comment by Felipefpl** [comment]
> Well, typical user maybe didn't notice anything, but console doesn't display message about Performance Observer now.
> Adding labels for example wouldn't work without Performance Observer.

I see, this wasnt explained in the changelog. :/

> Performance Observer works as intended, but GitHub also needs webcomponents support. Implementing that isn't that easy, especially that Mozilla done most work for Servo, which is disabled on Waterfox Classic. Moonchild has same problem.

Indeed pale moon/basilisk are the same as waterfox, i saw in html5test that only 2 of 10 webcomponents are implemented, why implementing those in waterfox is a hard thing to do?

> PS: For GitHub going to `about:config` and setting `dom.webcomponents.enabled` to `true` should be enough, but because :host() and some other things aren't implemented, some another websites may stop working.

I see, i'll wait till all things are implemented, thanks for your infos. :)

**Comment by hawkeye116477** [comment]
> i saw in html5test that only 2 of 10 webcomponents are implemented

This is not entirely true. That's the case when you have disabled webcomponents in `about:config` (default mode).
When you enable them (`dom.getRootNode.enabled`, `dom.webcomponents.enabled`), you'll see more, but it's not accurate. For example it shows that Shadow Dom is implemented, but it's partially implemented (ex https://developer.mozilla.org/en-US/docs/Web/CSS/:host() isn't working). 

The best method to test is going to http://wpt.live/ and choosing some tests for Shadow Dom, Custom Elements, etc.

**Comment by Felipefpl** [comment]
> 
> 
> > i saw in html5test that only 2 of 10 webcomponents are implemented
> 
> This is not entirely true. That's the case when you have disabled webcomponents in `about:config` (default mode).
> When you enable them (`dom.getRootNode.enabled`, `dom.webcomponents.enabled`), you'll see more, but it's not accurate. For example it shows that Shadow Dom is implemented, but it's partially implemented (ex https://developer.mozilla.org/en-US/docs/Web/CSS/:host() isn't working).
> 
> The best method to test is going to http://wpt.live/ and choosing some tests for Shadow Dom, Custom Elements, etc.

I understand now, thanks for the tips and links hawkeye. :)

**Comment by Felipefpl** [comment]
Since this issue was closed i'm curious to know if the oldest ones will be closed too since there are things there that must be fixed.
