### ISSUE TITLE
Closing all windows and then reopening app doesn't restore all windows in Windows 10

### ISSUE THREAD

**Issue by ylluminate** [MrAlex94/Waterfox#2031]
I run Waterfox on macOS and Windows 10 with "Restore previous session" enabled on each.  Reporting this issue with `G3.2.0 (64-bit)`. 

On macOS , when I close all windows with their accompanying tabs and then reopen Waterfox, all windows + their tabs are properly restored.  

When I do this on Windows 10 I find that only ONE window with its tabs are restored when I reopen Waterfox.  We very much need Waterfox to have this same behavior where all windows + tabs/sessions are restored for Windows.

**Comment by MrAlex94** [comment]
How are you closing on macOS? AFAIK you have to Quit the application via the dock for session restore to work on macOS.

On windows - terminating the process will restore all Windows as well, otherwise it will only restore the most recently closed Window before the process is terminated.

This may be a better bug for Mozilla than here.

**Comment by MrAlex94** [comment]
Since there hasn't been a reply in a while, please re-open if still facing on G4.
