### ISSUE TITLE
[Classic] Bad MP4 file crashes tab

### ISSUE THREAD

**Issue by Vulpovile** [MrAlex94/Waterfox#2032]
this video causes a crash in waterfox classic: https://tornadus.net/assets/video/how.mp4
Steps to reproduce:
Open waterfox classic
Open link
Crash

**Comment by Squall-Leonhart** [comment]
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/avc1/mp41)
File size                   : 457 KiB
Duration                    : 3 s 709 ms
Overall bit rate mode       : Variable
Overall bit rate            : 1 010 kb/s

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L6.2
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 4 frames
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 3 s 405 ms
Source duration             : 3 s 438 ms
Bit rate                    : 946 kb/s
Width                       : 42 pixels
Original width              : 12 000 pixels
Height                      : 42 pixels
Original height             : 12 000 pixels
Display aspect ratio        : 1.000
Frame rate mode             : Variable
Frame rate                  : 41.307 FPS
Minimum frame rate          : 8.263 FPS
Maximum frame rate          : 60.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 12.985
Stream size                 : 389 KiB (85%)
Source stream size          : 397 KiB (87%)
Writing library             : x264 core 161 r3027 4121277
Encoding settings           : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
mdhd_Duration               : 3404
Codec configuration box     : avcC

Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 3 s 709 ms
Bit rate mode               : Variable
Bit rate                    : 121 kb/s
Maximum bit rate            : 134 kb/s / 134 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 54.9 KiB (12%)
Default                     : Yes
Alternate group             : 1

issue is caused by attempting to hardware decode a profile that has no hardware support on any video card released so far.

most hardware codecs will have issues displaying it (visual issues)

**Comment by hawkeye116477** [comment]
Well, seems that on Linux it starts to play video, it's really small, but then it stops and on console error is shown  `Error Code: NS_ERROR_OUT_OF_MEMORY`.

**Comment by MrAlex94** [comment]
This shouldn't be causing a crash - I feel like it's more of a system codec issue. On macOS for example, it just refuses to play saying the file is corrupt.
