### ISSUE TITLE
Will we ever get that bootstrap addon host site?

### ISSUE THREAD

**Issue by 117649** [MrAlex94/Waterfox#2037]
tittle.

**Comment by hawkeye116477** [comment]
Well, I saw recently on reddit that even in next Waterfox ESR version support for bootstraped extensions will be removed, cuz no one mades them now... 
It's curious, because there a lot of that extensions on https://addons.basilisk-browser.org/extensions/, some extensions for WF Current are on some forums also (someone linked that on reddit or GH some time ago).

**Comment by MrAlex94** [comment]
Bootstrapped extension support won't be removed (it was just a discussion) - we've just been working on setting up an account system, without that we won't have the site live.
