### ISSUE TITLE
Waterfox G3 to G4 upgrade woes - General comment

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2335]
### What happened?

I want to make a comment because the issues that happened in the last 24 hours, also happened from Classic to G3.

For the last 15 years I have used all sorts of browsers, because we write software that we test in all browsers :  SeaMonkey, Firefox, Chrome, old Edge, new Edge, Opera, Waterfox.

It is only with  **Waterfox**, which happened to be my preferred browser, that I come across all these problems. 

**It really should not happen**

The most important testing in any software development is the one where there is a major upgrade.  We can all, all of us, tolerate minor issues, but to have a  **"Waterfox Limited"**  folder created on upgrade with none of your settings transferred, is just  **basic basic basic testing**  that was not done.  You can't get any more basic than that, and it was not done.  A look at the registry reveals even worse - Registry entries for  **"Waterfox",  "Waterfox Limited", "Waterfox Ltd", "Waterfox.net", and "WaterfoxLimited"** - it's crazy stuff !

These are the sort of things that completely turn off standard users as opposed to afficionados because standard home and office users have no time for this sort of thing : losing all their bookmarks, themes, preferences is a disaster to them.  We afficionados at least know how to backup these things, particularly from experience, but for standard users this is the lack of testing quality that turns all of them off.  **And it is not a one-off - the same thing happened from Classic to Current, and yet again from Current to G3, so there is a major fault line.**

I repeat :  no such nightmares with any of the other browsers.

O.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
I can appreciate the frustration, but this is the reason for the "soft" release. 

We did test profile thoroughly - this one slipped through because on testing for Windows, the browser needed to be closed and re-opened for it to use the "incorrect" location after upgrading. 

Since there were 3 other platforms we tested on without this issue, it did slip through. 

> And it is not a one-off - the same thing happened from Classic to Current

`Classic` → `Current` wasn't an issue, that was by design. We never upgraded anyone from Classic to Current and we kept profiles separate on purpose so people could run both in parallel.

`Current` → `G3` was an issue due to a new preference introduced by Mozilla. This was actually quite hard to track down and took a good while to find. The introduction of location specific profiles was an odd design choice.

Also this is an issue tracker not a discussion forum. Please use reddit if you want to make posts like these.

**Comment by Bielecki** [comment]
While I agree that it isn't the place to make such comments, I have to agree with OP. With every single browser restart I'm scared of updates, that will make me to manually recover session (again) and such things. While I know how to do that, a lot of people will not. You can't break people's work with almost every single update. 

With latest update I had to manually copy profiles from `~/.waterfox` to `~/.mozilla/.waterfox`, and while I got my session back I'm still struggling with not working certain extensions and that I am logged off on every single page. You just shouldn't do that. People will run off to Firefox, because it's now more stable experience than Waterfox.
