### ISSUE TITLE
Prowritingaid addon for Firefox/Chrome does not work on Waterfox

### ISSUE THREAD

**Issue by IamEhsan405** [MrAlex94/Waterfox#2343]
### What happened?

Hi, Can you help me with this?
The extension works on Firefox but not on Waterfox G4.0.0.1 x64

Here is the extension:
https://cdn.prowritingaid.com/browserextension/pwa-extension.xpi

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by IamEhsan405** [comment]
I tried it on a fresh Waterfox installed in the VM.

same result.

**Comment by MrAlex94** [comment]
@IamEhsan405, go to `about:config` and toggle `privacy.firstparty.isolate` to `false`. Restart Waterfox - the addon will start working. 

Please note that this will _decrease_ your privacy by default - but I may have to toggle it off for everyone since it's causing issues for others as well.

> Browser Damaged.

Quite the contrary - the browser is doing its job of protecting the user and making sure an add-on isn't overreaching.

Please re-open if you still have issues.
