### ISSUE TITLE
MacOS G4.0 update breaks Tree Style Tab add-on.

### ISSUE THREAD

**Issue by fastzombies** [MrAlex94/Waterfox#2352]
### What happened?

Waterfox auto-updated to latest G4 today and my essential Tree Style Tab extension now spins instead of populating with tabs.  I dug up a G3.2.6 MacOS dmg, re-isntalled and it is still broken.  I uninstalled the extension and re-installed and still broken.  I have a large number of tabs open.

There happened to be an old "Waterfox Current" app also on my system from November 2020 that somehow I never used.  It was never configured so it was a clean install.  Unfortunately it auto-updated but before restarted I installed Tree Style Tab and it worked fine after restart to G3.2.6, though only one tab was open.

Any ideas on what happened?  Is my Tree Style Tab data corrupted?  Any fix that doesn't involve wiping everything out and starting over?  Tree Style Tab is an essential add-on so I hope I can recover this.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)
G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS

**Comment by Shitennouji** [comment]
"Tree Style Tab" is a browser necessity for also me.
I am a Windows user (20H2) and had a similar problem after upgrading from G3 to G4.0.0.
The author of the extension clearly states that "it only supports Firefox, and does not support any other browser such as Waterfox".
I had no choice but to remove the Tree Style Tab.

When I applied the minor update "G4.0.1", it overwrote and updated the Profile in the previous directory (C:\Users\Username\AppData\Roaming\Waterfox\), and as a result, the Tree Style Tab was automatically enabled.
For reference: Profile folder of G4.0.0 (C:\Users\Username\AppData\Roaming\Waterfox Limited\Waterfox\)
This time, no conflicts are occurring. However, the background of the tab does not darken.

Since Firefox and LibreWolf, which I use regularly, do not have any problems even when "Lepton" is applied, I felt that the problem was with "Lepton" natively implemented in Waterfox 4th Generation, and applied "Lepton" to Firefox method, I manually added and run it, and all the problems were solved.
black7375/Firefox-UI-Fix: Lepton (old name: Proton Fix) | GitHub
https://github.com/black7375/Firefox-UI-Fix

I feel that this issue is due to the implementation of "Lepton".

My current using:
Windows 10 (x64) Version 20H2 (build 19042.1288)
Tree Style Tab 3.8.14
Waterfox 91.3.0 (x64 en-US)
LibreWolf 93.0 (64-bit en-US)
Firefox 78.15.0 ESR (x64 en-US)
Firefox Developer Edition 94.0b9 (64-bit en-US)
Firefox Nightly 95.0a1 (64-bit en-US)

**Comment by fastzombies** [comment]
Thank you for the reply.  I tried to update to G4.0.1 and it did not make any difference. I first uninstalled Tree Style Tab and reinstalled after update.  I cannot find where Tree Style Tab profile data is stored or I may try to delete that.

I suppose I should file a bug with the Tree Style Tab developer as well.

**Comment by SEE-ICT** [comment]
G4.0.5.1 breaks Tree Style Tab on Windows 10, too. At least for me. After an upgrade from Classic.

**Comment by MrAlex94** [comment]
You can now disable any Waterfox theme customisations in Settings > Look & Feel, which should prevent issues like this from occuring.
