### ISSUE TITLE
4th Generation Release 

### ISSUE THREAD

**Issue by JOArmyGirl** [MrAlex94/Waterfox#2377]
### What happened?

After the latest 64.0.0 update, I am unable to open Waterfox on my computer.  Click on icon and nothing happens.  Looked in my Task Manager, nothing there?? Help?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by InvisibleManX** [comment]
@JOArmyGirl

Most likely the problem is with your outdated CPU, and the fact that Waterfox decided to stop supporting them with G4. 

Use this tool (classic free version) to check if your CPU supports SSE 4.2 
https://www.cpuid.com/softwares/cpu-z.html

If it doesn't, then use this guide to decide what to do now: 
https://www.reddit.com/r/waterfox/comments/qcxfb7/

**Comment by Felipefpl** [comment]
> Use this tool (classic free version) to check if your CPU supports SSE 4.2 https://www.cpuid.com/softwares/cpu-z.html

A good question: why waterfox decided to stop supporting old CPUs? Why SSE 4.2 is needed now? No info was given about this, at least i didnt see any in the site.

**Comment by InvisibleManX** [comment]
@Felipefpl 
> A good question: why waterfox decided to stop supporting old CPUs? Why SSE 4.2 is needed now? No info was given about this, at least i didnt see any in the site.

All I got from the main developer MrAlex94 was this: 
https://github.com/WaterfoxCo/Waterfox/issues/2327#issuecomment-948734781
You can also read the continuation of discussion there. 

Also, as it's seen from this discussion on reddit: 
https://www.reddit.com/r/waterfox/comments/qcxfb7/two_options_what_to_do_if_your_cpu_doesnt_support/hhliprj/

it's not impossible to at least have G4 versions supporting older CPUs, but apparently would be too difficult, so that's why it's not being considered.

---
**The obivous conclusion:** MrAlex94 has a very futuristic vision for Waterfox, that it must stop supporting older CPUs (even the Core series that supports SSE 4.1 ) just to squeeze out of the browser a bit more performance on modern CPUs. 

Most people with their everyday tasks wouldn't even notice that increase in peformance, considering their CPUs are modern and fast enough as it is. The majority of performance falls on GPU anyway with hardware acceleration. 

**I personally don't think it's a good move, considering the following:** 

1. Waterfox's userbase is just 1/100 of Firefox's, and just 1/1000 of Chrome's userbase. So it's not a good idea to make such bold moves, making it less appealing than alternative browsers (including those two giants).
2. Firefox supports even SSE 2, and has no plans on stopping for now.
3. Chrome supports SSE 2 and plans on limiting their support to SSE 3 soon. 
4. Most big software giants these days try to limit their software to SSE 3. 
5. Only very modern games sometimes have the limit of SSE 4 (or specifically SSE 4.2), but it's reasonable, because it's expected that such games would be played on high-end modern PCs.

I'm not really sure what was gained by alienating a part of a small Waterfox's userbase. 
But to be fair I never was a developer of such a project.

**Comment by JOArmyGirl** [comment]
Thanks.  I'm tech savvy but not that tech savvy. LOL.  I just decided to re-install the previous version of Waterfox that I had on my computer.  Thanks for your help. JO.

**Comment by InvisibleManX** [comment]
@JOArmyGirl 
I see. 

Could you still get that CPU-Z tool (zip or installer version for classic one, whichver is convenient) and see there the list of your SSE supported (maybe post a creenshot here)? 

It doesn't require any technical knowledge. Just installing (or extracting from zip archive if you choose that one) and running it.

Or at least tell me what CPU you have on your computer, and I'll be able to say if it's the support issue or not.

I'm curious if the lack of SSE 4.2 support was really the cause.

**Comment by Felipefpl** [comment]
> I'm not really sure what was gained by alienating a part of a small Waterfox's userbase. But to be fair I never was a developer of such a project.

First, thank you VERY much for your detailed explanation, it was really informative. :)

Second, indeed, it doesnt make sense AT ALL... specially considerating what you said about firefox.
