### ISSUE TITLE
Content Process Limit option is missing from Settings

### ISSUE THREAD

**Issue by PapoyBanana** [MrAlex94/Waterfox#2417]
![image](https://user-images.githubusercontent.com/13683419/141189729-c0b0f5c7-3192-4f3f-8375-f84964bcdecb.png)

There used to be an option to choose the value of the content process limit there as an alternative to set the `dom.ipc.processCount` number via `about:config` page. Could you put it back?

**Comment by MrAlex94** [comment]
It's due to [Fission](https://wiki.mozilla.org/Project_Fission) being enabled by default on Waterfox, which means that this preference does nothing anymore. If you want the preference to re-appear, you'll need to disable it. You can change `fission.autostart` to `false` (then restart) to have the option re-appear.
