### ISSUE TITLE
extensions.getAddons.cache.enabled  has NO EFFECT  on the display of Themes in 4.0.2.1

### ISSUE THREAD

**Issue by Objectivite** [MrAlex94/Waterfox#2420]
### What happened?

Same bug again (Warning: only for programmers not taking offence to bugs being reported).

**extensions.getAddons.cache.enabled**  works in  **Firefox**.  Set it to  FALSE  in Firefox, and themes do not get previewed.  Set it to TRUE and themes get previewed **instantly** (ie. no need to wait for population).

More importantly :  I have all the same add-ons in Firefox (in addition to themes) as I have in Waterfox, so Firefox can handle all my themes and all my add-ons.

**extensions.getAddons.cache.enabled**  has  ZERO  effect in  **Waterfox 4.0.2.1**, as shown by the screenshots below.

![image](https://user-images.githubusercontent.com/89191739/141263729-4dcc5392-67d6-47ae-904c-325fc3ade199.png)

![image](https://user-images.githubusercontent.com/89191739/141266265-56bf77b0-8368-402f-b1bc-f2c7d2d818aa.png)

![image](https://user-images.githubusercontent.com/89191739/141264339-27a5732a-9717-4604-b1da-543694a03a02.png
[Objectivité_Waterfox_4.0.2.1_troubleshooting.txt](https://github.com/WaterfoxCo/Waterfox/files/7518956/Objectivite_Waterfox_4.0.2.1_troubleshooting.txt)
[Objectivité_Waterfox_4.0.2.1_troubleshooting_Raw_Data.txt](https://github.com/WaterfoxCo/Waterfox/files/7518974/Objectivite_Waterfox_4.0.2.1_troubleshooting_Raw_Data.txt)

O.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
That's how it works. I'd suggest filing a bug with Firefox if you want this fixed.
For example in Waterfox, when setting `extensions.getAddons.cache.enabled` to `true` by default, then installing a theme:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/4728920/143248459-2a4d9a83-e2e1-484e-a7f5-153547114d48.png">

Then disabling:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/4728920/143248636-381d8d39-2a9b-4425-bef1-1e243a98b5e8.png">

Then re-enabling:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/4728920/143248694-fdaff154-8225-4047-af51-a565686dc208.png">

And if you do the reverse with Firefox, by having `extensions.getAddons.cache.enabled` to `false` **first**:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/4728920/143248916-8a881fb5-9f54-4ab7-97b9-02f48da66584.png">
Then enabling it:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/4728920/143248993-7b4e6ac7-a59c-422f-a7d0-705bad2e67b1.png">

Low and behold, the same behaviour.

I'll say this one last time - opening a new issue instead of replying to us when we ask you for more information in a bug, will result in you being banned from opening another issue again. It's unnecessary and just creates more work.

**Comment by Objectivite** [comment]
I'll say it one last time :  **never assume** your users are idiots.

I reopened the issue exactly because I followed everything that was suggested and it was not working which is why I even added my troubleshooting data.

As it happens G4.3.0.1 has now fixed the problem.  As soon as the change is made, the themes show, instantly as in Firefox.  This is why I also included the themes I used, not the themes YOU want to test with.

Again, **do not assume your users are idiots** which is the running theme through so many of your replies, unlike the way Adam replies.

O.
