### ISSUE TITLE
Can't install Extenstions

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2439]
### What happened?

Hello,

Just wondering why I am not able to install the following extensions:

Microsoft Editor - Google Web Store

Microsoft Rewards - Google Web Store

MyStart Horse new tab - Google Web Store

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Ah, that will be because Waterfox doesn't support the `chrome_settings_overrides.search_provider.prepopulated_id` API. In fact, none of them do because they only support a chrome-specific API.

We have plans for the future to get this working, but don't hold your breath on it happening any time soon.
