### ISSUE TITLE
Rendering flicker when scrolling

### ISSUE THREAD

**Issue by rthom91** [MrAlex94/Waterfox#2519]
### What happened?

This issue does not exist on Waterfox 3.x. This issue also affects latest Firefox. I've submitted a bug report to Mozilla as well.

When duplicating screens using an El Gato (HD60S+) capture device, a major rendering issue appears when scrolling. It seems to be most visible on websites like Facebook and Youtube.

Video: https://www.youtube.com/watch?v=CCHIBFEonT0

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by Objectivite** [comment]
I second this - it is very visible on **YouTube** when you to go the YouTube homepage and simply scrolls through what YouTube is offering you today.

And, indeed, it happens in Firefox too.

I never reported it myself because I felt it might be something to do with the  **AdBlock Plus**  addin which I use in both Waterfox and Firefox, although I also have that addin in Microsoft Edge and Edge handles YouTube more smoothly.

O.

**Comment by MrAlex94** [comment]
Closed due to bug being filed upstream.
