### ISSUE TITLE
updated to wf-003 - 1.0: tabs aren't displayed

### ISSUE THREAD

**Issue by nofishonfriday** [MrAlex94/Waterfox#2521]
### What happened?

Hi,

I just updated to wf-003 - 1.0, it asked me to choose a theme on startup, chose dark theme, and now open tabs don't display.
Well I have the tab bar showing (I think), but no open tabs display.
Please see screenshot:
![wf](https://user-images.githubusercontent.com/7658194/147517004-cb819106-0211-4a4f-a7e8-fcbbac22afe2.jpg)

edit:
I noticed the tabs are there but misplaced (at the bottom).
![wf2](https://user-images.githubusercontent.com/7658194/147517668-8ef293b9-1d4d-4d27-83dd-6b967ea70753.jpg)

Just tried with G4.0.5.1, same issue.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by Objectivite** [comment]
Hmmm,

The problem you have is that you updated to a version prior to 4.0.4 when Adam corrected all the tabs and tab bar problems (they all work beautifully now).  And then you updated again to 4.5.0.1.

If you'd updated directly to 4.5.0.1 you probably would not have had this.

From experience, once you are in this mess, the only way you can correct it is to do  **about:profiles**  and create a new profile.  Before you do about:profiles, do a  **"Help\More Troubleshooting Information"**  to make a note of the location of your current profile so that when you are on the new profile you can go and import your old bookmarks and install your old add-ons.

![image](https://user-images.githubusercontent.com/89191739/147565602-f55e644f-3887-4676-a1d0-9a542f7606de.png)

O.

**Comment by nofishonfriday** [comment]
Hi,
thanks for the quick reply.

> The problem you have is that you updated to a version prior to 4.0.4 

Well, that's what the auto-updater offered me, I didn't download and install it manually (I don't know which version I was running prior to that though).

Anyway, I have done a Waterfox refresh meanwhile and things are back to normal, though I've lost all my extensions and their configs which was a bit unpleasant.
Closing as solved.
