### ISSUE TITLE
Not save logins/passwords CLOSED, NOT WORKING!!! Downgraded, installed latest Classic (all passw. ok), upgraded to G4, passwords empty!!! Problem NOT solved! Still!

### ISSUE THREAD

**Issue by UserMisterV** [MrAlex94/Waterfox#2543]
### What happened?

Hello!

After updated old version (56.2.10.7080) to latest 91.5.0.8046 (G4.0.6) not save logins. (System: Win7X64)

The problem:
After type login data, question: Save password? YES.
Settings, saved logins: EMPTY
Visit again this "saved login" site, retype again, save password? Yes...
Settings, saved logins: EMPTY

Not tested master password usage, all known main passwords not enough security for master (8-10 alphabetical & number & special character not enough)... unusable this function. Unknown password not set to all password lost.

All other old login info (stored 56.2.10.7080 version) only available usernames in login page, passwords empty.

Save it seems ok, really not save any data, list is empty.

"Create new login" button in about:logins after pressed, grayed out, not opened any input panel.
Full login/password manager unusable, not working!!!

All available external password manager/saver plugin only online service. I'm not send stranger sites all main password, not secure!
How to store login passwords in Waterfox to my computer only?

Thanks!

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
Hi there!

Between Waterfox 56 → G4, the password database format changed. 

The best way to “upgrade“ between these version is to go Waterfox 56 → [Waterfox Current 2020.10](https://cdn.waterfox.net/releases/win64/installer/Waterfox%20Current%202020.10%20Setup.exe) → Waterfox G4.

Waterfox Current will upgrade the password database when it detects it, then G4 will make use of the newer database.

**Comment by UserMisterV** [comment]
Ok, how to dowgrade to 56?

**Comment by juanitogan** [comment]
The short answer is, this is the upgrade path from Classic:

Classic --> [G3](https://cdn.waterfox.net/releases/) --> G5  (G3 will update to the latest Gx.x after 1 or more Waterfox restarts)

For example, I just successfully went through this and it kept all open windows and tabs (important to me [but also had a backup plan for]), and logins, and everything else:

Classic 2022.11 --> [G3.2.6](https://cdn.waterfox.net/releases/win64/installer/Waterfox%20G3.2.6%20Setup.exe) >auto> G5.0.1 >auto> G5.1.9

So, my question is:

**Since this is a known issue when coming from Waterfox Classic, why isn't both the issue and the workaround mentioned somewhere on the Waterfox G5 download page?????????**

As more and more sites start to utterly fail with Classic, this may come up more.

### Full Story

I started with this:

Classic 2022.11 --> G5.1.9 --> Oh, !!!, my logins are gone!

I then wasted about 10 hours over 2 days repeatedly reinstalling Classic and other versions to try and find the correct path.  (Hint: this also requires learning and resetting installs.ini and profiles.ini.)  The info here to go from Classic to Current 2020 was a near-total waste of time.  It only helped in that it gave me a clue that maybe another old version of Waterfox held the answer.

Here's the weird part of this that I discovered along the way:

If you take the Classic>G3>G5 route, then, in G5, you can import a Classic's logins.json file as a Firefox logins file (by copying it to an old Firefox profile folder) but not as a Classic logins file.  (But don't try this unless you are prepared for it to discard any logins you have already saved.)  If, however, you take the Classic>G5 route, you can't import that logins.json file any which way in G5.  Thus, it seems the import code is able to exist in G5 from G3, but it has been (1) lost along the way somewhere, and (2) not correctly set up to import from a Classic profile after the fact.

Also, trying to import a Classic profile in G5 when there are no unknown profiles to import (because it already imported the one you have) hangs the process.

Side Note: I use the Vertical Tabs Reloaded (VTR) plugin to, well, have vertical tabs.  I also hide the horizontal tab bar with CSS.  Anyhow, when I installed G3.2.6, all the tabs disappeared due to some issue with VTR (which also caused other error messages when restarting Waterfox) and, of course, the CSS still hiding the horizontal display.  I had a hunch, however, they were still open, so I left it alone.  Sure enough, when G3 upgraded to G5, all tabs were visible again in VTR.

(The final annoyance was I somehow lost all my Explorer++ tabs during all this.  Sigh.  That was a first... and curiously coincidental.  You just can't win it all.)
