### ISSUE TITLE
Waterfox not open after install

### ISSUE THREAD

**Issue by noponydeepweb** [MrAlex94/Waterfox#2548]
### What happened?

i have installed waterfox rn and when i open it crashes and nothing more happens

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by adonios77** [comment]
I have the same problem at both Win 7 & 10 (AMD Athlon(tm) 64 X2). 
The version that works on my (dual-boot) PC in both Win7 & Win10 is G323. 

_I give up my tries as it's hard to keep make my settings over again. 
I used Firefox since always and I could say: Firefox sucks, but the rests even more. (but sadly, all my "stuff" are there)
Waterfox gave me back what the Firefox ruined day by day._

**Comment by adamp01** [comment]
We are currently profiling installers built with different compile flags, and we may re-introduce support to non SSE4.2 instruction sets in a future release. As it stands right now, this is to be expected.

**Comment by adonios77** [comment]
By the way, I already use **G3.2.3** (64-bit) (Gecko 78.12.0), **as the main browser**, and I am quite **satisfied**, given the conditions.
