### ISSUE TITLE
Waterfox contacting pages without requests to do so.

### ISSUE THREAD

**Issue by Hunanbean** [MrAlex94/Waterfox#2553]
### What happened?

Waterfox is attempting to contact websites that i did not direct it to.
Freshly installed browser, no bookmarks, no history/cleared history. Set to open to blank page.
Without any user input, waterfox is contacting the following sites, while sitting on a blank page.
aus.waterfox.net
cdn.jsdelivr.net
cdn.statically.io
combinatronics.io
forcesafesearch.google.com
gitcdn.xyz
google.com
m.youtube.com
publicsuffix.org
push.services.mozilla.com
raw.githubhusercontent.com
restrict.youtube.com
restrictmoderate.youtube.com
shavar.services.mozilla.com
sitereview.zscaler.com
use-application-dns.net
www.google.com
www.youtube.com
www.youtube-nocookie.com
youtube.googleapis.com
youtubei.googleapis.com

Again, this is sitting on a blank page, with a new blank browser, with no user input. 
Is there a wiki type page that explains why Waterfox G4 is automatically attempting to contact all of these sites, while sitting idle on a blank page, with no cookies, no history, no bookmarks and no user input?

thanks

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
This is being looked into. Just to confirm, this was installed from the tarball on the website?

Also the following connections _should_ be expected (and a high level overview is in the [privacy policy](https://www.waterfox.net/docs/policies/privacy)):
 `aus.waterfox.net` -> Update server
 `push.services.mozilla.com` -> Used for Push Notifications that website might request access to
 `shavar.services.mozilla.com` -> Tracker blocklist
`use-application-dns.net` -> Related to Firefox's DNS-over-HTTPS plugin. This _should_ be disabled on Waterfox but I've seen a few times people mention that this is turned on for them.
`publicsuffixlist.org` -> Related to https://firefox-source-docs.mozilla.org/browser/urlbar/nontechnical-overview.html#the-heuristic-result. I wouldn't typically expect a call to the domain to happen for this.

The following I'd expect to see when connection to the Waterfox website (may also see when launching the browser for the first time and it shows the release notes):

`raw.githubhusercontent.com` -> API call on the website to generate the download link for Waterfox.

The unexpected ones:

```
cdn.jsdelivr.net
cdn.statically.io
combinatronics.io
forcesafesearch.google.com
gitcdn.xyz
google.com
m.youtube.com
restrict.youtube.com
restrictmoderate.youtube.com
www.google.com
www.youtube.com
www.youtube-nocookie.com
youtube.googleapis.com
youtubei.googleapis.com
```

The rest are not expected. Some of the connections seem related to network proxies (this may be due to DNS-over-HTTPS being on, will make sure we turn it off explicitly) and the other connections seem to be what you'd expect to see when going to YouTube or trying to perform a Google search for the first time.

We'll try to recreate on a fresh Linux install with OpenSnitch installed to see what connections are being made.

**Comment by Hunanbean** [comment]
The install is from https://aur.archlinux.org/packages/waterfox-g4-bin 
I came to essentially the same conclusions, hence the non-expected contacts were very surprising.

Thank you

**Comment by adamp01** [comment]
Meant to reply to this ages ago, apologies for the delay on that.

I monitored connections from a fresh install on Ubuntu (fresh VM) and had only expected connections: 
```
cdn.mozilla.net:
 - tracking-protection
 - content-signature-2
services.mozilla.net:
 - firefox.settings
 - push
 - shavar
```
Waterfox should not be attempting to contact anything else and I can only speculate that additional connections outside of these are from some form of contamination (most likely from a pre-existing profile). We certainly haven't added anything that would make requests to any Google owned domains

**Comment by Hunanbean** [comment]
Using a fresh OS and a fresh install of waterfox4-bin from the AUR, i am also only seeing expected connections. 
Thank you
