### ISSUE TITLE
Illegal instruction (core dumped) on current release with linux

### ISSUE THREAD

**Issue by Thyssenkrupp234** [MrAlex94/Waterfox#2558]
### What happened?

I downloaded the current waterfox release for linux, and upon running the `waterfox` executable file, it just gives an error in terminal: "Illegal instruction (core dumped)"

This usually happens with bad processor type or something, but i have a 64 bit processor with SSE4.2 intel core 2 duo. It should work fine. I am running linux mint cinnamon edition, version 20.3 with a 5.4.0-97-generic linux kernel.

Processor full name: Intel© Core™2 Duo CPU     T8300  @ 2.40GHz × 2

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Illegal instruction (core dumped)
```

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
The Santa Rosa line of processors [doesn't include SSE 4.2](https://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20Mobile%20T8300%20FF80577GG0563M%20(BX80577T8300).html) instruction set, it was added in Nehalem.

**Comment by Thyssenkrupp234** [comment]
Why does Waterfox require SSE 4.2? Firefox and almost every app available does not require this. And is there a way to recompile to support SSE4.2?

It should really support SSE4.1 and older, it shouldn't be too hard. All of my apps support SSE4.1 perfectly fine

**Comment by hawkeye116477** [comment]
`it shouldn't be too hard.`

It's not hard, but MrAlex wants to make it working the best on SSE 4.2 and that's not that easy if he would make it working for other instructions. He would need to make 2 versions - one for SSE 4.2 and one another and seems that he rather doesn't want to lose time for that double work.

As a alternative you can see one of my packages => https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage (AppImage or from apt repository), they work on other instructions and are additionally compiled with PGO+LTO (in speedometer test it looks like that's comparable to official build).

PS: On OBS there are no that very much good machines, so it would be rather impossible for me to build that same way just like MrAlex, but instead of that I'm adding PGO+LTO optimizations just like Mozilla does that.

**Comment by adamp01** [comment]
We are currently profiling installers built with different compile flags, and we may re-introduce support to non SSE4.2 instruction sets in a future release. As it stands right now, this is to be expected.
