### ISSUE TITLE
Can't play DRM content from Udemy. Works fine on latest Firefox.

### ISSUE THREAD

**Issue by klydeinside** [MrAlex94/Waterfox#2571]
### What happened?

The videos won't play for me. I have the DRM stuff enabled. It popped up and I allowed it. Have all the same stuff I had on Firefox. It works just fine there. 
![screen_121](https://user-images.githubusercontent.com/37005235/153691601-788b44a1-4696-47f0-8520-44c28ef8b443.png)

Any help? I don't want to have to use two different browsers for it. 

Thanks in advance

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.0.7 (Current)

### What platform are you seeing the problem on?

Windows

When you first goto the site on Firefox or any FF fork, it brings up this message. 
![](https://i.imgur.com/TW2cCMb.png)
I enable it and return later and it brings up the error in the original post. 

And here's the errors it brings up: This also happened on another FF fork I tried just an FYI. Works fine on regular FF though.
![](https://i.imgur.com/EicIz3G.png)

![](https://i.imgur.com/g8RM0GT.png)

**Comment by klydeinside** [comment]
I found a Waterfox version from 2 years ago and that doesn't work. And I tried a bunch of versions in between too. I guess it's been an issue for a while.

**Comment by adamp01** [comment]
Thanks for raising the issue and adding the error screenshots. Unfortunately there are a number of websites that have DRM related issues for Firefox forks. We've tried to resolve these in the past but never had much luck. I'll reach out to someone at Udemy to see if they can help root cause on their end, but typically there isn't much Waterfox can do to resolve these issues.
