### ISSUE TITLE
Security vulnerabilities in Firefox, is Waterfox affected?

### ISSUE THREAD

**Issue by Handsome-Rob** [MrAlex94/Waterfox#2601]
### What happened?

Firefox has released emergency updates due to security vulerbailities that allow remote code execution and escaping the sandbox, both of which are quite serious.

The first bug is CVE-2022-26485, which is a use-after-free problem in the browser’s XSLT parameter processing.

The second bug, CVE-2022-26486, is a use-after-free issue in the WebGPU IPC Framework.

The first bug is being exploited in the wild to gain remote code execution.

Is Waterfox also vulnerable to these bugs? Will Waterfox also be releasing emergency updates?

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by thunderstone135** [comment]
Hi, Waterfox is based on Firefox ESR. If you look [here](https://github.com/WaterfoxCo/Waterfox/commit/284e87eb7acd5e687c0db5c21fca698069456235), you will notice that it is currently at 91.7.0 ESR. According to this [article](https://www.mozilla.org/en-US/security/advisories/mfsa2022-09/), the vulnerabilities were fixed in 91.6.1 ESR. Since Waterfox is using the latest ESR, the security fixes in the previous version should be carried over to the latest version.

**Comment by adamp01** [comment]
@Handsome-Rob - Fixes for these bugs were included in G4.0.8 that was recently released.

For your reference, you can see that the fixes for these zero days are:
* [Bug 1758062](https://bugzilla.mozilla.org/show_bug.cgi?id=1758062)
* [Bug 1758070](https://bugzilla.mozilla.org/show_bug.cgi?id=1758070)
 Taken from:
* https://www.mozilla.org/en-US/security/advisories/mfsa2022-09/

You will be able to verify in our commit history that these are included., and you can compare against the diffs for the relevant bugs in the [ESR shortlog](https://hg.mozilla.org/releases/mozilla-esr91/shortlog).
