### ISSUE TITLE
Chrome add-ons do not work

### ISSUE THREAD

**Issue by scgf** [MrAlex94/Waterfox#2602]
### What happened?

Attempting to add a chrome extension only offers to open the extension in Chrome or save the .crx file somewhere. It is not possible to add it to Waterfox (G4.0.8).

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

**Comment by DavideCannonito** [comment]
I wanted to add that Opera addon's dont work either, as on my Reddit post:
https://www.reddit.com/r/waterfox/comments/td47mp/only_able_to_install_firefox_extentions/?utm_source=share&utm_medium=web2x&context=3
not even working on G3.2.5
![immagine](https://user-images.githubusercontent.com/52752208/158074647-548e46d2-f1c5-4a5b-a6e5-4623b19ef675.png)
![immagine](https://user-images.githubusercontent.com/52752208/158074650-f7f0b3c5-0d9d-4b90-9786-14f2cd70ff24.png)

**Comment by ihaddy** [comment]
Has this been fixed in commit ([#2625](https://github.com/WaterfoxCo/Waterfox/pull/2625))? I originally saw the closed issue on #2580 stating the team didn't have the resources to fix the broken chrome api compatibility, but i saw a reddit post from a waterfox dev claiming it had been fixed ~6 days ago and would be released but I don't think #2625 is included in the latest released binary.

I don't mind compiling it myself but i just wasn't sure if broad chrome addon compatibility had been restored in #2625 because of the wording from the dev on #2580. Thanks for any clarification!

**Comment by MrAlex94** [comment]
Yes, you should be able to use the Chrome Web Store now (although extensions for which we don't have API support for, won't work sadly).
