### ISSUE TITLE
Order changed when unmarking a tab as "Private Tab"

### ISSUE THREAD

**Issue by tgtn** [MrAlex94/Waterfox#2610]
### What happened?

Hello,

In a window I have a bunch of pinned tabs which are followed by 4 Private Tabs, and then a bunch of regular tabs.
When, on the first of these private tabs (LTR), I have unselected it as "Private Tab" (right click tab name -> v Private Tab) this one was changed to a regular tab, and it stayed in place. But when I have started to do the same for the 2nd, 3rd and 4th tabs, they were changed into regular tabs, but were placed at the end of the tab list.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
@tgtn - thanks for raising this.

What the Private Tab conversion is doing is actually creating a new tab inside the "Private" container, so the expected behaviour would be that the "new" tab would open after all your other tabs if you have your tab opening behaviour set as such (in `about:preferences`). So, assuming you have chosen new tab to open after all existing, the behaviour for tabs 2, 3 and 4 would be what we expect to happen. 

The behaviour for tab 1 is interesting and would not necessarily be expected, but it could be a result of if this tab was selected (in focus) and the others were not.

Regardless, I feel that a newly converted private tab (or private->normal) should maintain it's current position irrespective of user-defined tab opening settings. I'll add that to the to-do list.

**Comment by tgtn** [comment]
@adamp01 - I have checked the "Settings -> General -> Additional Tab Preferences -> Insert new tab after current tab" checkbox and indeed it was not checked (but I had an addon: "Open tabs next to current", as I wasn't aware of the built-in setting). So, after disabling the addon and rendering the "Insert new tab after current tab" setting active, I could no longer reproduce the reported bug.

**Comment by adamp01** [comment]
@tgtn  - Awesome - glad to hear that.
