### ISSUE TITLE
Page display/blurring 

### ISSUE THREAD

**Issue by newsjunkie247** [MrAlex94/Waterfox#2680]
### What happened?

Can anyone explain why this page has a weird blurring/display issue: https://pix11.com/news/local-news/brooklyn/why-new-yorkers-are-booking-rentals-they-dont-plan-to-stay-in-power-in-numbers/  It loads okay in troubleshooting mode, but it doesn't seem to have anything to do with extensions or hardware acceleration, and I have also tried independently to disable some javascript options, which also doesn't seem to make a difference. 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
@newsjunkie247 - Hi, this is caused by a default pref that Waterfox uses for our default theme to display correctly. You can go to `about:config` and change `layout.css.backdrop-filter.enabled` to `false` and it will fix the issues you are seeing. If you do notice any weird visual changes to the theme after doing this, that is the most likely cause.
