### ISSUE TITLE
Some questions about Waterfox

### ISSUE THREAD

**Issue by needlesslygrim** [MrAlex94/Waterfox#2704]
I couldn't create a GitHub issue that wasn't tagged ```feature_request``` or ```bug```, so sorry about that.

I have a few questions about what Waterfox is based on. I believe that it used to be based on Firefox ESR? However is the point of G4 is that is is based on the stable version of Firefox. Or, is it a hard fork of sorts that is just based on an older version of Firefox that is now going it's own way, while implementing upstream changes to Gecko? Thanks in advance

**Comment by thedoggybrad** [comment]
@ErickHoward 
Waterfox G4 uses the latest stable version of Firefox ESR. While, the Waterfox Classic uses an older version of Gecko which appears to be a Pre-Quantum version. 

Waterfox G4 is an ESR due to the fact that its releases are almost nearing the same version 91 on both browsers. Firefox ESR is using version 91 in its latest release and Waterfox's user agent reports version 91 in its latest release. This is according to my previous observations.

Yes it is based on Firefox ESR but there are differences like the defaults and more features like Chrome extension support.

**Comment by thedoggybrad** [comment]
@ErickHoward Just a clarification (In case you did not know what are the differences of G4 and Classic)

The G4 has a goal to be a modern browser.
The Classic one has a goal to maintain an older version of Gecko while having security patches from the latest versions. Note: There are a lot of unpatched problems in Classic.

So to be more secure, use the G4.

**Comment by needlesslygrim** [comment]
@thedoggybrad Does that mean that Waterfox is significantly less secure than Firefox (non-ESR) ? Or is it much the same due to security patches.

**Comment by thedoggybrad** [comment]
@ErickHoward 
Firefox ESR was designed to be stable while not having a lot of features. While the Firefox (Non-ESR) is designed to recieve all the features and updates. 

As of now Firefox ESR is using version 91 while the Firefox Non-ESR is using version 100. There are delays of updates in the ESR. 


Meaningly, Firefox Non-ESR recieves the patches first. Then after it will move to Firefox ESR and lastly Waterfox G4 will patch the updates from the ESR. If you are willing to just wait for delays there is no problem for you.

I perfer not to answer your question about who is more secure as they all recieve the updates from the same source. What we are talking about here is the delay of receiving the patches.

**Comment by needlesslygrim** [comment]
@thedoggybrad So it's pretty much on a par with Mainline Firefox right, for features and security?

**Comment by thedoggybrad** [comment]
I think so, yes just the problem is the delays of security patches.

**Comment by needlesslygrim** [comment]
I see, thanks for information.
