### ISSUE TITLE
Cant edit the text in the search bar

### ISSUE THREAD

**Issue by uqus** [MrAlex94/Waterfox#2833]
### What happened?

I can type, I can select the query but I am not able to select the part of the query.
Firefox and prev versions works fine.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by ziebarthj** [comment]
**Further Information**
This issue is also present on the Windows version of Waterfox G5.0 and G5.0.1.  You cannot use the mouse to place the cursor anywhere inside the search box query.  It will only select the whole query.

**Reproducible?**

I have reproduced this on multiple Windows 10 computers.

**Version**

Waterfox G5.0 and G5.0.1

**What platform are you seeing the problem on?**

Windows 10

**Relevant log output**

_No response_

**Comment by MrAlex94** [comment]
👋 You can fix this by disabling support for the `search` input type.

`about:config` → `layout.forms.input-type-search.enabled` → `false`

**Comment by rubycorn** [comment]
It doesnt resolve the problem.

**Comment by uqus** [comment]
It works, restart is required. Thank you.

**Comment by ziebarthj** [comment]
Agreed.  This bug is resolved by turning off the setting mentioned and restarting the browser.

**Comment by NotesTracker** [comment]
I too was getting frustrated by this, so thanks for the solution. I wouldn't have determined this-in a month of Sundays. As a matter of interest, why was this particular setting changed on G5, and does it have implications elsewhere in G5?
