### ISSUE TITLE
KeepassXC Autofill Plugin Key Exchange Failure

### ISSUE THREAD

**Issue by Jelloeater** [MrAlex94/Waterfox#2847]
### What happened?

Please note I brought this up with the plugin devs, they said to reach out to the Waterfox team.
Love your browser, just seems like G5 broke the plugin.

Here's the related bug ticket from the other devs.
https://github.com/keepassxreboot/keepassxc-browser/issues/1742

## Expected Behavior

Database connects and auto fills in Websites

## Current Behavior

When trying to connect extension, getting: Key exchange was not successful. Error in browser

## Possible Solution

Can try rolling back to previous version of Waterfox.
Plugin works fine on Firefox 105.0.2 (64bit)
Also works fine on Waterfox G4.1.5
Does NOT work on Waterfox G5.0.1

## Steps to Reproduce (for bugs)

1. Try and autofill website

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2.2
Operating system: MacIntel (Actually M1)
Browser: Mozilla Firefox 102.0 (Actually G5 5.0.1)

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.4
CPU architecture: arm64
Kernel: darwin 21.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

### Reproducible?

- [x] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by krivine** [comment]
I found the same issue, and confirm that the connection is successful on Firefox and Waterfox G4.0.2.1. I'm running Linux.

**Comment by Jelloeater** [comment]
I can also confirm that Waterfox G5.0.1 on Windows 10 w/ KeePassHttp-Connector 1.0.11 and KeePass 2.50 works just fine.
https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/

**Comment by Jelloeater** [comment]
Looks like this is just a Waterfox issue only w/ G5 unfortunately.
@krivine You're running KeePassXC, right?

**Comment by krivine** [comment]
@Jelloeater Yes, I run KeePassXC.

**Comment by adamp01** [comment]
Thanks for reporting - I'll hopefully be able to take a look some time this week.

**Comment by Jelloeater** [comment]
Thanks @adamp01 any info you need, please let me know!

**Comment by marcelmaltry** [comment]
I had to remove my database from the plugin, copy `org.keepassxc.keepassxc_browser.json` from the respective Firefox directory to the Waterfox directory as described [here](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#1-after-enabling-browser-integration-and-support-for-your-browser), and then connect to the database again.

**Comment by krivine** [comment]
@marcelmaltry Thank you so much! That works.

**Comment by adamp01** [comment]
Altenatively, you could symlink as well:
`ln -s ~/Library/Application\ Support/Mozilla/NativeMessagingHosts ~/Library/Application\ Support/Waterfox/NativeMessagingHosts`

**Comment by TankedThomas** [comment]
This is still broken for me.
I'm on Arch Linux with kernel 6.0.2, using KeePassXC 2.7.1.
I've also got the same issue on macOS 12.6.1 (using KeePassXC 2.7.3), but no other browser config with which to try the fix, so I'm mainly troubleshooting on Linux for now. 
I have it installed on Windows 10 too but it's not set up, so I can't comment on that.

I had Waterfox G4 installed via AUR (package `waterfox-g4-bin`) and replaced it with G5 via `waterfox-g-bin` - I synced settings with Mozilla's servers and manually set up the rest, so there shouldn't be any chance of corruption.

I tried copying over `/usr/lib/mozilla/native-messaging-hosts/` to `/usr/lib/waterfox/` but with no luck - I still get the same error about a failed key exchange. Then I tried KeePassXC's "custom browser configuration", which just gives me errors, even when I created ~/.config/waterfox and copied the `native-messaging-hosts` directory but it doesn't work. 

I should also add that I removed G4 since I thought G5 was working fine (I've been using it on Windows and macOS since it came out and it's fine, but only just got around to upgrading on Linux), so it's possible that the current `org.kde.plasma.browser_integration.json` is just a placeholder/template file (it certainly doesn't seem to contain any identifying information).

With all that being said, linking a previous setup doesn't really fix the problem, because if the browser is the only one installed, you can't setup a database in the first place.

Something worth noting more than possibly everything else is that the KDE Plasma Integration extension (connects to Arch package `plasma-desktop-integration`) has the same problem where it fails to connect. I could be wrong, but this seems to me like a larger problem than just a KeePassXC issue - there seems to be some specific issue within G5 that is causing this behaviour.

**Comment by csylvain** [comment]
had similar problem with G5.0.2 on freshly updated Ubuntu 22.04.1 - "Key exchange not successful"

my fix:
```
cp -pvr ~/.mozilla/native-messaging-hosts/ ~/.waterfox
```

(i switched to Waterfox because of the 'Firefox snap' policy)
browser integration is fully functional now.

**Comment by Jelloeater** [comment]
I was able to get that Symlink hack to work on my home Ubuntu box, just had to install Firefox and link the DB there first... annoying, but it works.
`ln -s ~/.mozilla/native-messaging-hosts ~/.waterfox/native-messaging-hosts`
