### ISSUE TITLE
Waterfox fails to load anything on ShaderToy

### ISSUE THREAD

**Issue by Megalomaniak** [MrAlex94/Waterfox#2921]
### What happened?

Fails to load any shader example on shadertoy.com with "Error loading shader"

Developer Tools Console tells me:

domPolicy 
Object { permissions: {…}, cascaded: false, navigationURL: "https://www.shadertoy.com/view/Ms2fWW" }
 loading https://www.shadertoy.com/view/Ms2fWW 1670182588449:0.35492785406987915 
Object { on: on(eventName, listener), detach: detach(eventName, listener), fire: fire(eventName, listener), fetchPolicy: fetchPolicy(sync), fetchLikeNoTomorrow: fetchLikeNoTomorrow(url, setup), setup: setup(policy), policy: {…}, allows: allows(cap), embeddingDocument: false, pendingSyncFetchPolicy: true, … }
4d8c2871-6509-4f75-87dc-b8468b975315:16:15

Some cookies are misusing the recommended “SameSite“ attribute 3
Google Analytics and Tag Manager is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713687 for details. sandbox eval code:1:9

WebGL (2.0=true): Asynch Compile: no, Textures: F32 [yes], F16 [yes], Depth [yes], LOD [yes], Aniso [yes], Units [32], Max Size [16384], Cube Max Size [16384], Targets: MRT [yes], F32 [yes], Max Size [16384] Ms2fWW:2573:33

Uncaught TypeError: jsn is null
    updatepage https://www.shadertoy.com/view/Ms2fWW:22459
    onload https://www.shadertoy.com/view/Ms2fWW:22227
Ms2fWW:22459:23

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
domPolicy 
Object { permissions: {…}, cascaded: false, navigationURL: "https://www.shadertoy.com/view/Ms2fWW" }
 loading https://www.shadertoy.com/view/Ms2fWW 1670182588449:0.35492785406987915 
Object { on: on(eventName, listener), detach: detach(eventName, listener), fire: fire(eventName, listener), fetchPolicy: fetchPolicy(sync), fetchLikeNoTomorrow: fetchLikeNoTomorrow(url, setup), setup: setup(policy), policy: {…}, allows: allows(cap), embeddingDocument: false, pendingSyncFetchPolicy: true, … }
4d8c2871-6509-4f75-87dc-b8468b975315:16:15
Some cookies are misusing the recommended “SameSite“ attribute 3
Google Analytics and Tag Manager is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713687 for details. sandbox eval code:1:9
WebGL (2.0=true): Asynch Compile: no, Textures: F32 [yes], F16 [yes], Depth [yes], LOD [yes], Aniso [yes], Units [32], Max Size [16384], Cube Max Size [16384], Targets: MRT [yes], F32 [yes], Max Size [16384] Ms2fWW:2573:33
Uncaught TypeError: jsn is null
    updatepage https://www.shadertoy.com/view/Ms2fWW:22459
    onload https://www.shadertoy.com/view/Ms2fWW:22227
Ms2fWW:22459:23
```

**Comment by DavidSchillinger** [comment]
I assume that:
- You're using https://www.shadertoy.com/view/Ms2fWW to test this
- "fails to load anything on ShaderToy" means that the canvas doesn't play a video for you

If those assumptions are not correct then you might want to clarify the issue.

I'm on G5.1.2 (Windows 11) and the canvas/video/shader plays for me.
No noteworthy console output besides some WebGL warnings:
```
WebGL warning: texSubImage: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.
WebGL warning: texSubImage: Tex image TEXTURE_2D level 0 is incurring lazy initialization. 
```

That said `Uncaught TypeError: jsn is null` (shown in your console) is a JS/script error on the website that probably crashes the rest of the page causing the shader to fail to play. This is, IMO, highly unlikely to be caused by Waterfox.

I'd suggest you check that you don't have an extension blocking/editing any scripts or network requests (you could turn off extensions one-by-one). At first glance, the code that uses `jsn` appears to be used for the comments on the page, which might help you with tracking down the issue.

Finally, it's worth mentioning that the page's name is "Shadertoy *BETA*". So maybe there's a bug on the website. I think this is still more likely than it being a Waterfox bug, so I'd suggest raising this with the Shadertoy website maintainers if you can confirm that extensions aren't causing this.

EDIT: If you are logged-in on the website, you could try logging out and then refreshing the page (as some of the comment section data is based on your login session). If this fixes the problem then it's more likely to be an issue with Shadertoy than with Extensions or Waterfox.

**Comment by Megalomaniak** [comment]
@DavidSchillinger I chased down [another issue](https://github.com/webcompat/web-bugs/issues/103590) recently regarding pcpartpicker.com and it turned out to be in regards to the _HTTP Referrer header_ setting set to `send the referrer header only when clicking on links and similar elements` causing a similar issue of most of the page contents not loading. 

The fact that the shader I had linked has an issue of it's own is unrelated. Pretty sure the issue I was experiencing in OP was related to the same HTTP Referrer header setting. But well timed reply, I likely would have forgotten to check back on this otherwise.
