### ISSUE TITLE
Consider building in JPEG-XL support

### ISSUE THREAD

**Issue by jobbautista9** [MrAlex94/Waterfox#2924]
Currently, there's an `about:config` option for JPEG-XL support, but it doesn't do anything at the moment. It would be nice if Waterfox adds in the `--enable-jxl` option in the standard mozconfig. The decoding works fine, though alpha, animations, HDR, color profiles, and progressive decoding aren't supported yet (all of which except HDR have pending patches in Mozilla phabricator which we could apply ourselves in our fork btw, see the depends of [bug 1539075](https://bugzilla.mozilla.org/show_bug.cgi?id=1539075)). AVIF was shipped without support for animations either, so why should JPEG-XL be different?

I think having JPEG-XL support out-of-the-box would be a nice selling point of the browser, and help Waterfox differentiate itself from its parent.

**Comment by MrAlex94** [comment]
Done! https://github.com/WaterfoxCo/Waterfox/commit/4e1dca751406fe4a71435f2088c9ac4eae7d41ad

**Comment by jobbautista9** [comment]
Thank you! :D

**Comment by louie-github** [comment]
Does this actually enable JXL out-of-the-box? Looking at [moz.configure](https://github.com/WaterfoxCo/Waterfox/blob/4e1dca751406fe4a71435f2088c9ac4eae7d41ad/toolkit/moz.configure#L692), there may be a Nightly check that you have to disable:

```python
@depends("--disable-jxl", milestone.is_nightly)
def jxl(value, is_nightly):
    if is_nightly and value:
        return True
```

**Comment by Nulled-Out** [comment]
> Does this actually enable JXL out-of-the-box? Looking at [moz.configure](https://github.com/WaterfoxCo/Waterfox/blob/4e1dca751406fe4a71435f2088c9ac4eae7d41ad/toolkit/moz.configure#L692), there may be a Nightly check that you have to disable:
> 
> ```python
> @depends("--disable-jxl", milestone.is_nightly)
> def jxl(value, is_nightly):
>     if is_nightly and value:
>         return True
> ```

So, to just set it as false and submit in a new PR?

**Comment by RobertZenz** [comment]
As a heads up, enabling JPEG XL support seems to break various websites in G5.1.1, for example [MagicHolz](https://magicholz.de/).

With enabled JPEG XL support (`image.jxl.enabled` set to `true`) various images on the website do not load anymore. As far as I can see, that is because the PNG images are treated as JPEG XL, for some reason. I can reproduce the same with Firefox 108, however, in Firefox `image.jxl.enabled` seems to default to `false` which means you have to toggle it to see the issue.

**Comment by louie-github** [comment]
As far as I can tell, that's because [MagicHolz](https://magicholz.de/) runs on Shopify, which **actually** serves JPEG XL (jxl) images if the browser sends the `Accept: image/jxl` header, which Firefox does whenever `image.jxl.enabled` is set to `true`, even on Stable, where it is not built with JXL support.

Actually, Shopify seems to serve JXL, AVIF, or WebP images even if the CDN link ends in ".png", which is a bit confusing.

See [the comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1178058#c79) from Shopify on the bug tracker for Chromium for reference:
> Several months ago, Shopify added automatic JPEG XL support to the platform. Since early summer, all merchant stores on Shopify have been JPEG XL enabled for those with the Chrome feature flag enabled. We are eager for this feature to I2S.

This just confirms the fact that we need to remove the Nightly check in [moz.configure](https://github.com/WaterfoxCo/Waterfox/blob/4e1dca751406fe4a71435f2088c9ac4eae7d41ad/toolkit/moz.configure#L692) for it to work.

**Comment by RobertZenz** [comment]
> As far as I can tell, that's because [MagicHolz](https://magicholz.de/) runs on Shopify, which actually serves JPEG XL (jxl) images if the browser sends the Accept: image/jxl header, which Firefox does whenever image.jxl.enabled is set to true, even on Stable, where it is not built with JXL support.
 > 
 > Actually, Shopify seems to serve JXL, AVIF, or WebP images even if the CDN link ends in ".png", which is a bit confusing.

I see, thank you very much for the information.

Wait, does that mean that Waterfox G5.1.1 ist built *without* JPEG XL support but the setting defaults to `true` (tested in a new profile)? Or did I miss that this issue is about that?

**Comment by louie-github** [comment]
Yes, it seems that `image.jxl.enabled` is set to `true` by default. It's set in [000-waterfox.js](https://github.com/WaterfoxCo/Waterfox/blob/4e1dca751406fe4a71435f2088c9ac4eae7d41ad/waterfox/browser/app/profile/000-waterfox.js#L98).

Since the flag only works on Nightly builds, the regular Release builds of Waterfox have broken JPEG XL support, leading to those missing image issues you mentioned before.

**Comment by RobertZenz** [comment]
Should I open an extra issue for that?

**Comment by RobertZenz** [comment]
I see, thank you.
