### ISSUE TITLE
Unsupported browser on netflix Widevine may need to be updated 

### ISSUE THREAD

**Issue by mikeloeven** [MrAlex94/Waterfox#2925]
### What happened?

Netflix no longer works with current version G5.1 Widevine update is probably needed 

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by ghost** [comment]
I don't think it is a Widevine issue, but rather more the simple solution that Waterfox G5.1 runs on an older version of the Firefox base, which I _think_ is 102.0 (while the latest version is 107.0.1). 

I'm getting a similar issue whilst trying to use Prime Video, but it mentions nothing about Widevine and instead that I'm using an outdated version of Firefox.

Widevine _could_ be a secondary issue though, as G5.1 runs on version 4.10.2449.0 instead of 4.10.2557.0 like reported by the current version of Firefox.

The only real temporary solution is to use Firefox for the time being for video streaming until Waterfox gets updated to a newer Firefox base.

**Comment by mikeloeven** [comment]
TBH if it was only that changing the user agent should bypass the prompt the fact that this does not work usually means its being triggered by an older widevine plugin and not the browser its self

**Comment by MrAlex94** [comment]
This has been fixed in G5.1.1. You'll need to either wait for the plugin to update (no idea how long that will take) or force update it:

Preferences page → General → Files and Applications and un-check "Play DRM-controlled content". Wait for a few seconds, then re-check the box. The DRM plugin should update.

Widevine Plugin should be 4.10.2557.0.

**Comment by MrAlex94** [comment]
G5.1.7 on Windows fully supports DRM now, with other platforms following suit soon.
