### ISSUE TITLE
Font display blurs in G5.1.1

### ISSUE THREAD

**Issue by gwin7ok** [MrAlex94/Waterfox#2953]
### What happened?

G4.1.5 environment

gfx.webrender.force-disabled;true → fonts are not blurred
![G4 1 5_true](https://user-images.githubusercontent.com/1727775/210118462-6fe622d1-5ded-4e23-af81-977815a32bb8.jpg)

gfx.webrender.force-disabled;false → fonts are blurred
![G4 1 5_false](https://user-images.githubusercontent.com/1727775/210118492-c18c80e1-ce0c-4ec0-aff3-67ded4f24c7e.jpg)

G5.1.1 Environment

gfx.webrender.force-disabled;true → fonts are blurred
![G5 1 1_true](https://user-images.githubusercontent.com/1727775/210118517-549fb086-eff1-4944-8a52-63703a2db66a.jpg)

gfx.webrender.force-disabled;false → fonts are blurred
![G5 1 1_false](https://user-images.githubusercontent.com/1727775/210118533-808d443a-ebe3-48d1-a3ec-bc83ca04085f.jpg)

Firefox ver.108.0.1 without gfx.webrender.force-disabled setting → Fonts do not blur
![ss005 - GitHub - WaterfoxCo／Waterfox： The official Waterfox ？？ source code repository ？ Mozilla Firefox](https://user-images.githubusercontent.com/1727775/210118600-0a7926f4-c895-4225-98c3-7fdba452d14a.jpg)

*G4.1.5, G5.1.1, and Firefox108.0.1 were tested after running "Refresh Waterfox"

Windows 10 settings
![ss002 - Settings](https://user-images.githubusercontent.com/1727775/210118638-cd492832-430c-410d-81a3-227d1acc38c1.jpg)
![ss001 - Settings](https://user-images.githubusercontent.com/1727775/210118642-da6c0a98-3eac-40b5-bffe-c421f4a96c58.jpg)

Waterfox DPI settings
![ss003 - 053WaterfoxG main2 Properties](https://user-images.githubusercontent.com/1727775/210118647-ca1d7fff-ada8-4d1c-9fa3-a0b50f89b98f.jpg)
![ss004 - 053WaterfoxG main2 Properties](https://user-images.githubusercontent.com/1727775/210118650-6f0e77ad-6a0f-4d48-a694-f5e44a38dc56.jpg)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by gwin7ok** [comment]
G5.0 Environment

gfx.webrender.force-disabled;true → fonts are blurred
gfx.webrender.force-disabled;false → fonts are blurred

**Comment by DavidSchillinger** [comment]
I don't know if this helps at all, but on G5.1.2 I don't have a `gfx.webrender.force-disabled` config option.
Has this option been renamed/removed/replaced maybe?

**Comment by gwin7ok** [comment]
G5.1.2 Environment

gfx.webrender.force-disabled;true → fonts are blurred
gfx.webrender.force-disabled;false → fonts are blurred

**Comment by MarcvsMalvs** [comment]
I’m new to Waterfox, but I’ve known this blur for years from… Microsoft Edge!
From what I’ve known, this has _nothing to do with Windows dpi scaling_ and everything to do with the browser’s accelerated rendering incompatibility with certain GPUs and their drivers.
While I’ve never observed this issue in any stable release of Google Chrome, it was well obvious to me from their detailed GPU-related settings that they have carefully disabled certain parts of GPU-accelerated rendering for certain GPU/drivers. Interestingly enough, Microsoft has not gone through the same diligence with Edge, and I had to uncheck their ‘Use hardware acceleration’ option.

When it comes to Firefox/Waterfox, I’ve just recently installed Firefox 109, for reference and comparison, and I’m not going to install 102 ESR along with it…
But there is no blur for me in Firefox 109 with ‘performance defaults’ enabled, while in Waterfox 5.1.2, I had to uncheck ‘performance defaults’ and uncheck ‘use hardware acceleration’.

Since Firefox 109 doesn’t have the same issue, it means primarily that they have been able to figure out the right combination of settings for certain thus affected GPUs, just like Google did with Chrome.

My GPU is a dated Kepler-based Nvidia Quadro, with drivers that Nvidia no longer keeps current.

**Comment by goodusername123** [comment]
This sounds like it could very much be a driver profile related issue as "waterfox.exe" is not recognized by the nvidia gpu drivers while "firefox.exe" has it's own special profile.

I would highly recommend downloading this: https://github.com/Orbmu2k/nvidiaProfileInspector
and adding "**waterfox.exe**" to the "**Mozilla Firefox**" profile which should hopefully solve the problem.

**Comment by gwin7ok** [comment]
After changing the motherboard and CPU, the font no longer blurs
Old composition: MSI Z390-A PRO & Intel Core i5-9400F
New composition: MSI X570-A PRO & AMD Ryzen 5 3600X
