### ISSUE TITLE
Rakuten Viki is not playing content

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2963]
### What happened?

A bug happened!

I think the title says it all. No video can be played on Rakuten Viki's website with an error saying that browser is not compatible. As shown below

![Capture](https://user-images.githubusercontent.com/107793471/213691471-11c8ccd3-964d-45e1-af31-63a0008e3a24.PNG)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by DavidSchillinger** [comment]
The website appears to require minimum Firefox 106 (102 is the base for G5.1.2) because the message disappears when I feed it a Firefox 106 user agent (I tested 102-108). The website then crashes though. I suppose it makes use of some feature introduced in that version (it included some major WebRTC changes).

I didn't poke further as there doesn't seem to be anything to do here besides waiting for Waterfox's Firefox base to be bumped?

**Comment by ghost** [comment]
> The website appears to require minimum Firefox 106 (102 is the base for G5.1.2) because the message disappears when I feed it a Firefox 106 user agent (I tested 102-108). The website then crashes though. I suppose it makes use of some feature introduced in that version (it included some major WebRTC changes).
> 
> I didn't poke further as there doesn't seem to be anything to do here besides waiting for Waterfox's Firefox base to be bumped?

OK
Thank you for the clarification. 
So it means it'll take some time before waterfox gets that bump to reach this (106) base.
