### ISSUE TITLE
G6: UI issues

### ISSUE THREAD

**Issue by yokoffing** [MrAlex94/Waterfox#3099]
### What happened?

The toggle box not showing when checked is a bit jarring. I'm testing on my old Macbook. Unsure if 1) it occurs outside of macOS or 2) if this is intentional.

![Screenshot 2023-08-02 at 1 14 43 PM](https://github.com/WaterfoxCo/Waterfox/assets/11689349/02a91e87-ed84-4814-8a2d-1650b657adbf)

![Screenshot 2023-08-02 at 1 18 01 PM](https://github.com/WaterfoxCo/Waterfox/assets/11689349/d2d691df-5344-41f7-a50b-2e43a9e0b576)

Borders for text boxes also missing.

![Screenshot 2023-08-02 at 1 20 27 PM](https://github.com/WaterfoxCo/Waterfox/assets/11689349/8a1d13f7-dd77-4ef6-a378-b08c0e3c480f)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

macOS

**Comment by yokoffing** [comment]
The Tracking Protection toggle on doesn't show any color either.

![ETP water G6](https://github.com/WaterfoxCo/Waterfox/assets/11689349/1a3e8e47-795b-4fd0-a4e6-62aa3b91f35e)

**Comment by yokoffing** [comment]
![Screenshot 2023-08-08 at 11 43 02 PM](https://github.com/WaterfoxCo/Waterfox/assets/11689349/e8a21da6-f112-4ce3-ab81-772691a3d861)

Bookmark star in Dark Theme

**Comment by MrAlex94** [comment]
@black7375 - is it worth us reporting this in the [Firefox-UI-Fix ](https://github.com/black7375/Firefox-UI-Fix) repo?

**Comment by black7375** [comment]
I'll check it out when this issue is over!!

- https://github.com/black7375/Firefox-UI-Fix/issues/744

**Comment by black7375** [comment]
I just installed Waterfox G6.
The problem is the setting that should only be applied when it is below the Firefox v102.
(G6 seems to be based on Firefox v115)

Change the following settings #2877
- `userChrome.compatibility.accent_color` to `false`

---

Lepton `v8.0.0` has many changes due to Mozilla's discontinuation of Win7/8 support at FF v117.
After version `v8.0.0` is released, you can use the ESR version files(`leptonChromeESR.css`, `leptonContentESR.css`)

- https://github.com/black7375/Firefox-UI-Fix/tree/dev/css

**Comment by MrAlex94** [comment]
Thanks @black7375 for the feedback, will get that remedied ASAP!

**Comment by yokoffing** [comment]
Fixed in Beta 3
