### ISSUE TITLE
Weather radar I use doesn't work on Waterfox G6

### ISSUE THREAD

**Issue by SuperHirmu** [MrAlex94/Waterfox#3209]
### What happened?

Tested with clean install of Waterfox G6.0.3, also clean install of Firefox v118.0.1.

Affected site: https://www.ursa.fi/ursa/jaostot/myrskybongaus/ursa_radar.php?map=1

Expecting to see: weather radar, instead broken image.

No amount of adjusting privacy, dns etc. settings will make it work on Waterfox.

Works fine on Firefox and any other browser including earlier Waterfox generations, just not Waterfox G6.

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by SuperHirmu** [comment]
Left: latest Firefox

Right: latest Waterfox

![fox](https://github.com/WaterfoxCo/Waterfox/assets/48919623/c546f537-f856-4ce4-9074-a1f6cfb8f48f)

**Comment by strotee** [comment]
It works for me. (Waterfox 6.0.3 - Win 10 19044.3448)

**Comment by SuperHirmu** [comment]
It's good if it works for you, but that state of affairs is very poor consolation to all those who aren't that privileged. From top level comments we can already determine something's seriously wrong with Waterfox G6, because it fails even basic tasks, basics of web as it is. This release was ill-advised, and I wish I could go back to G5, but that's likely not possible. Sites not loading or content not showing, whereas parent Firefox does, that's enough of a clue.

**Comment by ghost** [comment]
The images do _not_ display for me either. I am using G6.0.3 on Linux Mint 21.2.

While viewing the web page, I opened Web Developer Tools and selected the Inspector Tab. I noticed that there were 50 errors listed similar to the following:

Blocked loading mixed display content "http://www.ursa.fi/ursa/jaostot/myrskybongaus/apps/sadetutkakartat/piirto/map_1/2023-10-08T10:05:00Z.jpg"

If I open that image on its own in a new tab it works fine. Is Waterfox rejecting the images because they use 'http://', while the page uses 'https://'?

I checked my setting for 'HTTPS-Only Mode' and found it is set to 'Don't enable HTTPS-Only Mode'.

Next to each error message there is a 'Learn More' link that goes to: https://developer.mozilla.org/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

**UPDATE**
I found that changing the setting for `security.mixed_content.block_display_content` to `false` in `about:config` enables the images to be displayed.

However, this may make your browser less secure.

I have just checked my laptop, which is still running G5.1.13, and found that it has `security.mixed_content.block_display_content` set to `false` by default. It displays the radar images OK.

**Comment by MrAlex94** [comment]
As reticulatus has mentioned, in G6 Waterfox has started to block mixed content from loading. It's a security risk, and one websites shouldn't be putting users in the way of.

You are free to revert the preference, but this isn't something I want to have left disabled.

There _should_ be a browser UI component letting the user know this is happening though, so I will see if this is something I can add myself.

You can find out more information about mixed content [here](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content).

> An HTTPS page that includes content fetched using cleartext HTTP is called a mixed content page. Pages like this are only partially encrypted, leaving the unencrypted content accessible to sniffers and man-in-the-middle attackers. That leaves the pages unsafe.
