### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by DutchPete** [MrAlex94/Waterfox#3413]
### What happened?

You state on your webpage "Telemetry is disabled within the browser", yet on the about:config page there is a telemetry item with a ClientID.
What do you need that for? To me it seems you are tracking me around the web.
Firefox does the same.

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Hi,

Which IDs specifically? If it's ones such as `toolkit.telemetry.cachedClientID`, they're just randomly generated, because they're never used (you'll see `toolkit.telemetry.enabled` is `false` and locked).

There's no point rummaging into the code to stop them running as well, because that just adds maintenance burden for something that essentially does nothing.

As long as the modules are disabled at build time and the top level pref is turned off, it shouldn't be doing anything.

**Comment by DutchPete** [comment]
Yep, it is `toolkit.telemetry.cachedClientID`. So, OK, no worries. Thanks for your feedback.

**Comment by MrAlex94** [comment]
No problem 👍
